import 'package:mongo_dart/mongo_dart.dart';

void adCitys () async {
  var db = Db("mongodb://localhost:27017/lens_map");
await db.collection('countries').insertMany([{
'name': 'Spain',
'citys_sp': [
{'cityname': 'Adeje'},
{'cityname': 'Adra'},
{'cityname': 'Aguadulce'},
{'cityname': 'Alicante'},
{'cityname': 'Aguilas'},
{'cityname': 'Ajalvir'},
{'cityname': 'Alameda'},
{'cityname': 'Alcala de Guadaira'},
{'cityname': 'Alcala de Henares'},
{'cityname': 'Alcala la Real'},
{'cityname': 'Alcanar'},
{'cityname': 'Alcantarilla'},
{'cityname': 'Alcaraz'},
{'cityname': 'Alcázar de San Juan'},
{'cityname': 'Alcoi'},
{'cityname': 'Alcobendas'},
{'cityname': 'Alcorcon'},
{'cityname': 'Alcoy'},
{'cityname': 'Alcudia'},
{'cityname': 'Aldaia'},
{'cityname': 'Alfafar'},
{'cityname': 'Algeciras'},
{'cityname': 'Algemesi'},
{'cityname': 'Alhaurin de la Torre'},
{'cityname': 'Alhaurin el Grande'},
{'cityname': 'Alhama de Murcia'},
{'cityname': 'Aljaraque'},
{'cityname': 'Almagro'},
{'cityname': 'Almanza'},
{'cityname': 'Almazora'},
{'cityname': 'Almensilla'},
{'cityname': 'Almonte'},
{'cityname': 'Almoradi'},
{'cityname': 'Almunecar'},
{'cityname': 'Alozaina'},
{'cityname': 'Alpedrete'},
{'cityname': 'Altura'},
{'cityname': 'Alzira'},
{'cityname': 'Amorebieta'},
{'cityname': 'Amposta'},
{'cityname': 'Anchuelo'},
{'cityname': 'Andorra'},
{'cityname': 'Andujar'},
{'cityname': 'Anguiano'},
{'cityname': 'Antigua'},
{'cityname': 'Aranda de Duero'},
{'cityname': 'Aranjuez'},
{'cityname': 'Archena'},
{'cityname': 'Arcos de la Frontera'},
{'cityname': 'Arganda del Rey'},
{'cityname': 'Arges'},
{'cityname': 'Arinaga'},
{'cityname': 'Arona'},
{'cityname': 'Arrecife'},
{'cityname': 'Arriate'},
{'cityname': 'Arroyo de la Miel'},
{'cityname': 'Astorga'},
{'cityname': 'Avila'},
{'cityname': 'Aviles'},
{'cityname': 'Azpeitia'},
{'cityname': 'Baeza'},
{'cityname': 'Bailen'},
{'cityname': 'Balaguer'},
{'cityname': 'Baños de la Encina'},
{'cityname': 'Barbastro'},
{'cityname': 'Barcelona'},
{'cityname': 'Barreiros'},
{'cityname': 'Baza'},
{'cityname': 'Beas de Granada'},
{'cityname': 'Beas de Segura'},
{'cityname': 'Begues'},
{'cityname': 'Benasal'},
{'cityname': 'Benicarlo'},
{'cityname': 'Benidorm'},
{'cityname': 'Benifaio'},
{'cityname': 'Benijofar'},
{'cityname': 'Benimodo'},
{'cityname': 'Benissa'},
{'cityname': 'Benito'},
{'cityname': 'Berja'},
{'cityname': 'Bermeo'},
{'cityname': 'Betanzos'},
{'cityname': 'Bollullos de la Mitación'},
{'cityname': 'Bollullos Par del Condado'},
{'cityname': 'Borja'},
{'cityname': 'Bormujos'},
{'cityname': 'Bornos'},
{'cityname': 'Botarell'},
{'cityname': 'Briviesca'},
{'cityname': 'Brunete'},
{'cityname': 'Buenavista del Norte'},
{'cityname': 'Buñol'},
{'cityname': 'Burgos'},
{'cityname': 'Burlada'},
{'cityname': 'Burmester'},
{'cityname': 'Burriana'},
{'cityname': 'Cabeza del Buey'},
{'cityname': 'Cabezón de la Sal'},
{'cityname': 'Cabra'},
{'cityname': 'Cadiz'},
{'cityname': 'Calañas'},
{'cityname': 'Calanda'},
{'cityname': 'Calasparra'},
{'cityname': 'Calatayud'},
{'cityname': 'Calella'},
{'cityname': 'Callosa de Segura'},
{'cityname': 'Callosa d’En Sarria'},
{'cityname': 'Camas'},
{'cityname': 'Campo de Criptana'},
{'cityname': 'Candelaria'},
{'cityname': 'Canet de Berenguer'},
{'cityname': 'Canet de Mar'},
{'cityname': 'Cañete de las Torres'},
{'cityname': 'Cangas de Narcea'},
{'cityname': 'Cangas del Narcea'},
{'cityname': 'Cañete de las Torres'},
{'cityname': 'Canillo'},
{'cityname': 'Cantillana'},
{'cityname': 'Caravaca de la Cruz'},
{'cityname': 'Carballo'},
{'cityname': 'Carboneras'},
{'cityname': 'Cardedeu'},
{'cityname': 'Carmona'},
{'cityname': 'Carranque'},
{'cityname': 'Carrascosa del Campo'},
{'cityname': 'Cartagena'},
{'cityname': 'Cártama'},
{'cityname': 'Casarabonela'},
{'cityname': 'Casarrubuelos'},
{'cityname': 'Casares'},
{'cityname': 'Caspe'},
{'cityname': 'Castril'},
{'cityname': 'Castro del Rio'},
{'cityname': 'Castro Urdiales'},
{'cityname': 'Castrojeriz'},
{'cityname': 'Catalonia'},
{'cityname': 'Catarroja'},
{'cityname': 'Caudete'},
{'cityname': 'Cehegin'},
{'cityname': 'Ceuta'},
{'cityname': 'Cieza'},
{'cityname': 'Ciudad Real'},
{'cityname': 'Clariana'},
{'cityname': 'Cocentaina'},
{'cityname': 'Colmenar'},
{'cityname': 'Colmenar Viejo'},
{'cityname': 'Colmenarejo'},
{'cityname': 'Collado Villalba'},
{'cityname': 'Conil de la Frontera'},
{'cityname': 'Córdoba'},
{'cityname': 'Coria del Rio'},
{'cityname': 'Coslada'},
{'cityname': 'Costitx'},
{'cityname': 'Crespos'},
{'cityname': 'Cuenca'},
{'cityname': 'Cullera'},
{'cityname': 'Daimiel'},
{'cityname': 'Daimus'},
{'cityname': 'Denia'},
{'cityname': 'Dos Hermanas'},
{'cityname': 'Durango'},
{'cityname': 'Ecija'},
{'cityname': 'El Astillero'},
{'cityname': 'El Boalo'},
{'cityname': 'El Campello'},
{'cityname': 'El Ejido'},
{'cityname': 'El Espinar'},
{'cityname': 'El Masnou'},
{'cityname': 'El Palmar'},
{'cityname': 'El Parador de las Hortichuelas'},
{'cityname': 'El Puerto de Santa María'},
{'cityname': 'El Rosario'},
{'cityname': 'El Saucejo'},
{'cityname': 'El Viso del Alcor'},
{'cityname': 'Elche'},
{'cityname': 'Elda'},
{'cityname': 'Elx'},
{'cityname': 'Emperador'},
{'cityname': 'Encamp'},
{'cityname': 'Enix'},
{'cityname': 'Ermua'},
{'cityname': 'Esparreguera'},
{'cityname': 'Espartinas'},
{'cityname': 'Esplugues de Llobregat'},
{'cityname': 'Estella'},
{'cityname': 'Estepona'},
{'cityname': 'Etxebarri'},
{'cityname': 'Felanitx'},
{'cityname': 'Ferrol'},
{'cityname': 'Figueres'},
{'cityname': 'Firgas'},
{'cityname': 'Fisterra'},
{'cityname': 'Fitero'},
{'cityname': 'Fortuna'},
{'cityname': 'Fregenal de la Sierra'},
{'cityname': 'Fresno de la Ribera'},
{'cityname': 'Frigiliana'},
{'cityname': 'Fuengirola'},
{'cityname': 'Fuente Alamo de Murcia'},
{'cityname': 'Fuenlabrada'},
{'cityname': 'Fuentes de Andalucia'},
{'cityname': 'Gandia'},
{'cityname': 'Garachico'},
{'cityname': 'Garrucha'},
{'cityname': 'Gava'},
{'cityname': 'Gibraltar'},
{'cityname': 'Gijon'},
{'cityname': 'Girona'},
{'cityname': 'Granada'},
{'cityname': 'Granja de Rocamora'},
{'cityname': 'Guadalajara'},
{'cityname': 'Guadalupe'},
{'cityname': 'Guadix'},
{'cityname': 'Guamasa'},
{'cityname': 'Guardo'},
{'cityname': 'Guaro'},
{'cityname': 'Guardamar del Segura'},
{'cityname': 'Guillena'},
{'cityname': 'Haro'},
{'cityname': 'Hellin'},
{'cityname': 'Hernani'},
{'cityname': 'Hinojosa del Duque'},
{'cityname': 'Horcajo de Santiago'},
{'cityname': 'Horcajo de la Sierra'},
{'cityname': 'Horcajo de los Montes'},
{'cityname': 'Horcajuelo de la Sierra'},
{'cityname': 'Huesca'},
{'cityname': 'Huelva'},
{'cityname': 'Huercal de Almeria'},
{'cityname': 'Huercal-Overa'},
{'cityname': 'Icod de los Vinos'},
{'cityname': 'Iglesuela del Cid'},
{'cityname': 'Igualada'},
{'cityname': 'Illescas'},
{'cityname': 'Illora'},
{'cityname': 'Ingenio'},
{'cityname': 'Ingles'},
{'cityname': 'Irun'},
{'cityname': 'Isla Cristina'},
{'cityname': 'Isora'},
{'cityname': 'Isla Plana'},
{'cityname': 'Ituren'},
{'cityname': 'Iznajar'},
{'cityname': 'Iznatoraf'},
{'cityname': 'Jaén'},
{'cityname': 'Javea'},
{'cityname': 'Jerez de la Frontera'},
{'cityname': 'Jijona'},
{'cityname': 'Jodar'},
{'cityname': 'Jumilla'},
{'cityname': 'Jun'},
{'cityname': 'La Algaba'},
{'cityname': 'La Almunia de Doña Godina'},
{'cityname': 'La Antilla'},
{'cityname': 'La Coruña'},
{'cityname': 'La Frontera'},
{'cityname': 'La Gomera'},
{'cityname': 'La Lantejuela'},
{'cityname': 'La Línea de la Concepción'},
{'cityname': 'La Luisiana'},
{'cityname': 'La Mata'},
{'cityname': 'La Oliva'},
{'cityname': 'La Palma del Condado'},
{'cityname': 'La Puebla de Almoradiel'},
{'cityname': 'La Roda'},
{'cityname': 'La Romana'},
{'cityname': 'La Solana'},
{'cityname': 'La Taha'},
{'cityname': 'La Union'},
{'cityname': 'La Vall de Uxo'},
{'cityname': 'Lanjaron'},
{'cityname': 'Laredo'},
{'cityname': 'Las Galletas'},
{'cityname': 'Las Norias de Daza'},
{'cityname': 'Las Palmas de Gran Canaria'},
{'cityname': 'Las Rozas de Madrid'},
{'cityname': 'Las Torres de Cotillas'},
{'cityname': 'Lazkao'},
{'cityname': 'Laza'},
{'cityname': 'Lebrija'},
{'cityname': 'Lekeitio'},
{'cityname': 'Leon'},
{'cityname': 'Lerma'},
{'cityname': 'Linares'},
{'cityname': 'Lleida'},
{'cityname': 'Loeches'},
{'cityname': 'Lora del Rio'},
{'cityname': 'Lorcha'},
{'cityname': 'Los Alcázares'},
{'cityname': 'Los Barrios'},
{'cityname': 'Los Corrales'},
{'cityname': 'Los Corrales de Buelna'},
{'cityname': 'Los Cristianos'},
{'cityname': 'Los Llanos de Aridane'},
{'cityname': 'Los Monteros'},
{'cityname': 'Los Palacios y Villafranca'},
{'cityname': 'Los Realejos'},
{'cityname': 'Lozoya'},
{'cityname': 'Lozoyuela'},
{'cityname': 'Lucena'},
{'cityname': 'Lugo'},
{'cityname': 'Lumbreras'},
{'cityname': 'Luque'},
{'cityname': 'Madrid'},
{'cityname': 'Magan'},
{'cityname': 'Mahón'},
{'cityname': 'Malaga'},
{'cityname': 'Mancha Real'},
{'cityname': 'Mancha Vieja'},
{'cityname': 'Manises'},
{'cityname': 'Manlleu'},
{'cityname': 'Playa de Aro'},
{'cityname': 'Pobla de Farnals'},
{'cityname': 'Pobla de Vallbona'},
{'cityname': 'Poble Nou del Delta'},
{'cityname': 'Pobra do Caramiñal'},
{'cityname': 'Ponferrada'},
{'cityname': 'Pont de Suert'},
{'cityname': 'Pontecesures'},
{'cityname': 'Porcuna'},
{'cityname': 'Porriño'},
{'cityname': 'Portals Nous'},
{'cityname': 'Portillo'},
{'cityname': 'Portugalete'},
{'cityname': 'Pozo Alcon'},
{'cityname': 'Pozoblanco'},
{'cityname': 'Pozuelo de Alarcon'},
{'cityname': 'Pozo Estrecho'},
{'cityname': 'Priego de Cordoba'},
{'cityname': 'Pruna'},
{'cityname': 'Puçol'},
{'cityname': 'Puebla de Cazalla'},
{'cityname': 'Puebla de Don Fadrique'},
{'cityname': 'Puebla de Sancho Perez'},
{'cityname': 'Puebla del Rio'},
{'cityname': 'Puente Genil'},
{'cityname': 'Puerto de la Cruz'},
{'cityname': 'Puerto de la Duquesa'},
{'cityname': 'Puerto de Mazarron'},
{'cityname': 'Puerto de Sagunto'},
{'cityname': 'Puerto del Carmen'},
{'cityname': 'Puerto Lumbreras'},
{'cityname': 'Puigcerda'},
{'cityname': 'Puig de Ros'},
{'cityname': 'Punta Prima'},
{'cityname': 'Purullena'},
{'cityname': 'Quart de Poblet'},
{'cityname': 'Quesada'},
{'cityname': 'Rafal'},
{'cityname': 'Ramales de la Victoria'},
{'cityname': 'Redondela'},
{'cityname': 'Requena'},
{'cityname': 'Reus'},
{'cityname': 'Ribadeo'},
{'cityname': 'Rianxo'},
{'cityname': 'Ribarroja del Turia'},
{'cityname': 'Riba-roja de Turia'},
{'cityname': 'Rincon de la Victoria'},
{'cityname': 'Rincón de la Victoria'},
{'cityname': 'Rivas-Vaciamadrid'},
{'cityname': 'Roales'},
{'cityname': 'Roales de Campos'},
{'cityname': 'Roquetas de Mar'},
{'cityname': 'Rota'},
{'cityname': 'Rubi'},
{'cityname': 'Rute'},
{'cityname': 'Sabadell'},
{'cityname': 'Sabero'},
{'cityname': 'Sada'},
{'cityname': 'Sagunto'},
{'cityname': 'Salamanca'},
{'cityname': 'Salceda de Caselas'},
{'cityname': 'Salinas'},
{'cityname': 'Salobrena'},
{'cityname': 'Salteras'},
{'cityname': 'San Adrian'},
{'cityname': 'San Agustin'},
{'cityname': 'San Bartolome'},
{'cityname': 'San Bartolomé de Tirajana'},
{'cityname': 'San Cristobal de La Laguna'},
{'cityname': 'San Fulgencio'},
{'cityname': 'San Javier'},
{'cityname': 'San Juan'},
{'cityname': 'San Lorenzo de El Escorial'},
{'cityname': 'San Luis de Sabinillas'},
{'cityname': 'San Martin de Valdeiglesias'},
{'cityname': 'San Mateo'},
{'cityname': 'San Miguel'},
{'cityname': 'San Miguel de Abona'},
{'cityname': 'San Pedro de Alcantara'},
{'cityname': 'San Pedro del Pinatar'},
{'cityname': 'San Roque'},
{'cityname': 'San Sebastian'},
{'cityname': 'San Vicente del Raspeig'},
{'cityname': 'Sanxenxo'},
{'cityname': 'Sant Andreu de la Barca'},
{'cityname': 'Sant Antoni de Portmany'},
{'cityname': 'Sant Boi de Llobregat'},
{'cityname': 'Sant Carles de la Ràpita'},
{'cityname': 'Sant Cugat del Vallès'},
{'cityname': 'Sant Feliu de Guixols'},
{'cityname': 'Sant Feliu de Llobregat'},
{'cityname': 'Sant Joan d’Alacant'},
{'cityname': 'Sant Just Desvern'},
{'cityname': 'Sant Pere de Ribes'},
{'cityname': 'Santa Brigida'},
{'cityname': 'Santa Coloma de Gramenet'},
{'cityname': 'Santa Cruz de Tenerife'},
{'cityname': 'Santa Eulalia del Rio'},
{'cityname': 'Santa Lucia'},
{'cityname': 'Santa Margarida de Montbui'},
{'cityname': 'Santa Maria de Palautordera'},
{'cityname': 'Santa Maria del Cami'},
{'cityname': 'Santa Pola'},
{'cityname': 'Santa Ponsa'},
{'cityname': 'Santa Susanna'},
{'cityname': 'Santiago de Compostela'},
{'cityname': 'Santiago del Teide'},
{'cityname': 'Santomera'},
{'cityname': 'Santurtzi'},
{'cityname': 'Sant Vicenç dels Horts'},
{'cityname': 'Santanyi'},
{'cityname': 'Santarem'},
{'cityname': 'Santovenia de Pisuerga'},
{'cityname': 'Santpedor'},
{'cityname': 'Sanxenxo'},
{'cityname': 'Sarria'},
{'cityname': 'Sarriguren'},
{'cityname': 'Seseña'},
{'cityname': 'Seville'},
{'cityname': 'Sierra'},
{'cityname': 'Sierra de Yeguas'},
{'cityname': 'Siete Aguas'},
{'cityname': 'Silos'},
{'cityname': 'Sineu'},
{'cityname': 'Sitges'},
{'cityname': 'Sollana'},
{'cityname': 'Soller'},
{'cityname': 'Solsona'},
{'cityname': 'Son Servera'},
{'cityname': 'Sopelana'},
{'cityname': 'Soria'},
{'cityname': 'Sorihuela'},
{'cityname': 'Sotillo de la Adrada'},
{'cityname': 'Suances'},
{'cityname': 'Sueca'},
{'cityname': 'Tabernas'},
{'cityname': 'Tacoronte'},
{'cityname': 'Talavera de la Reina'},
{'cityname': 'Talavera la Real'},
{'cityname': 'Taradell'},
{'cityname': 'Tarazona'},
{'cityname': 'Tarragona'},
{'cityname': 'Tarrega'},
{'cityname': 'Tegueste'},
{'cityname': 'Tejina'},
{'cityname': 'Telde'},
{'cityname': 'Tenerife'},
{'cityname': 'Teror'},
{'cityname': 'Terrassa'},
{'cityname': 'Teruel'},
{'cityname': 'Tetuan'},
{'cityname': 'Tias'},
{'cityname': 'Tibi'},
{'cityname': 'Tijoco Bajo'},
{'cityname': 'Tinajo'},
{'cityname': 'Tineo'},
{'cityname': 'Tobarra'},
{'cityname': 'Tolox'},
{'cityname': 'Tomares'},
{'cityname': 'Tomelloso'},
{'cityname': 'Tordesillas'},
{'cityname': 'Torre del Mar'},
{'cityname': 'Torre Pacheco'},
{'cityname': 'Torreperogil'},
{'cityname': 'Torrequebrada'},
{'cityname': 'Torrelavega'},
{'cityname': 'Torrelodones'},
{'cityname': 'Torremolinos'},
{'cityname': 'Torremuelle'},
{'cityname': 'Torreperogil'},
{'cityname': 'Torres Torres'},
{'cityname': 'Torrevieja'},
{'cityname': 'Torroella de Montgri'},
{'cityname': 'Torrox'},
{'cityname': 'Tortosa'},
{'cityname': 'Totana'},
{'cityname': 'Touro'},
{'cityname': 'Trigueros'},
{'cityname': 'Trujillo'},
{'cityname': 'Tui'},
{'cityname': 'Ubeda'},
{'cityname': 'Ugena'},
{'cityname': 'Ulldecona'},
{'cityname': 'Ulldecona'},
{'cityname': 'Utebo'},
{'cityname': 'Utrera'},
{'cityname': 'Valdemoro'},
{'cityname': 'Valdepeñas'},
{'cityname': 'Valderrobres'},
{'cityname': 'Valdoviño'},
{'cityname': 'Valencia'},
{'cityname': 'Valencina de la Concepción'},
{'cityname': 'Valga'},
{'cityname': 'Valle de Tabladillo'},
{'cityname': 'Vallecas'},
{'cityname': 'Vall de Boi'},
{'cityname': 'Valladolid'},
{'cityname': 'Valle Gran Rey'},
{'cityname': 'Valle Guerra'},
{'cityname': 'Vallehermoso'},
{'cityname': 'Valls'},
{'cityname': 'Valverde'},
{'cityname': 'Valverde del Camino'},
{'cityname': 'Valsequillo'},
{'cityname': 'Valsequillo de Gran Canaria'},
{'cityname': 'Vélez de Benaudalla'},
{'cityname': 'Velez-Malaga'},
{'cityname': 'Vélez-Rubio'},
{'cityname': 'Vera'},
{'cityname': 'Vera de Moncayo'},
{'cityname': 'Verin'},
{'cityname': 'Vic'},
{'cityname': 'Vigo'},
{'cityname': 'Vilaboa'},
{'cityname': 'Viladecans'},
{'cityname': 'Vilagarcia de Arousa'},
{'cityname': 'Vilalba'},
{'cityname': 'Vilamarxant'},
{'cityname': 'Vilanova i la Geltru'},
{'cityname': 'Vilanova del Cami'},
{'cityname': 'Villablanca'},
{'cityname': 'Villabona'},
{'cityname': 'Villacanas'},
{'cityname': 'Villacarrillo'},
{'cityname': 'Villadiego'},
{'cityname': 'Villagonzalo Pedernales'},
{'cityname': 'Villajoyosa'},
{'cityname': 'Villalba del Alcor'},
{'cityname': 'Villalpando'},
{'cityname': 'Villaluenga de la Sagra'},
{'cityname': 'Villanueva de la Concepcion'},
{'cityname': 'Villanueva de la Serena'},
{'cityname': 'Villanueva de los Castillejos'},
{'cityname': 'Villanueva del Ariscal'},
{'cityname': 'Villanueva del Arzobispo'},
{'cityname': 'Villanueva del Rey'},
{'cityname': 'Villanueva del Rio'},
{'cityname': 'Villanueva del Rio y Minas'},
{'cityname': 'Villanueva del Rosario'},
{'cityname': 'Villanueva de Tapia'},
{'cityname': 'Villanueva de la Torre'},
{'cityname': 'Villanueva de los Infantes'},
{'cityname': 'Villanueva Mesia'},
{'cityname': 'Villaralto'},
{'cityname': 'Villareal'},
{'cityname': 'Villarejo de Salvanés'},
{'cityname': 'Villarreal'},
{'cityname': 'Villarrubia'},
{'cityname': 'Villarrubia de los Ojos'},
{'cityname': 'Villarrobledo'},
{'cityname': 'Villarroya de los Pinares'},
{'cityname': 'Villasequilla'},
{'cityname': 'Villaviciosa'},
{'cityname': 'Villaviciosa de Odon'},
{'cityname': 'Villena'},
{'cityname': 'Villoldo'},
{'cityname': 'Vinaros'},
{'cityname': 'Vinaròs'},
{'cityname': 'Vitoria-Gasteiz'},
{'cityname': 'Vizcaya'},
{'cityname': 'Xabia'},
{'cityname': 'Xativa'},
{'cityname': 'Xeraco'},
{'cityname': 'Xirivella'},
{'cityname': 'Yunquera'},
{'cityname': 'Zafra'},
{'cityname': 'Zamora'},
{'cityname': 'Zaragoza'},
{'cityname': 'Zubia'},
{'cityname': 'Zumaia'},
{'cityname': 'Zumarraga'},
{'cityname': 'Zuñeda'},
],
'top_citys_sp': [
{'cityname': 'Barcelona'},
{'cityname': 'Madrid'},
{'cityname': 'Sevilla'},
{'cityname': 'Valencia'},
{'cityname': 'Zaragoza'},
],
}]);}



List spainCitis = [
    'Adeje',
    'Adra',
    'Aguadulce',
    'Alicante',
    'Aguilas',
    'Ajalvir',
    'Alameda',
    'Alcala de Guadaira',
    'Alcala de Henares',
    'Alcala la Real',
    'Alcanar',
    'Alcantarilla',
    'Alcaraz',
    'Alcázar de San Juan',
    'Alcoi',
    'Alcobendas',
    'Alcorcon',
    'Alcoy',
    'Alcudia',
    'Aldaia',
    'Alfafar',
    'Algeciras',
    'Algemesi',
    'Alhaurin de la Torre',
    'Alhaurin el Grande',
    'Alhama de Murcia',
    'Aljaraque',
    'Almagro',
    'Almanza',
    'Almazora',
    'Almensilla',
    'Almonte',
    'Almoradi',
    'Almunecar',
    'Alozaina',
    'Alpedrete',
    'Altura',
    'Alzira',
    'Amorebieta',
    'Amposta',
    'Anchuelo',
    'Andorra',
    'Andujar',
    'Anguiano',
    'Antigua',
    'Aranda de Duero',
    'Aranjuez',
    'Archena',
    'Arcos de la Frontera',
    'Arganda del Rey',
    'Arges',
    'Arinaga',
    'Arona',
    'Arrecife',
    'Arriate',
    'Arroyo de la Miel',
    'Astorga',
    'Avila',
    'Aviles',
    'Azpeitia',
    'Baeza',
    'Bailen',
    'Balaguer',
    'Baños de la Encina',
    'Barbastro',
    'Barcelona',
    'Barreiros',
    'Baza',
    'Beas de Granada',
    'Beas de Segura',
    'Begues',
    'Benasal',
    'Benicarlo',
    'Benidorm',
    'Benifaio',
    'Benijofar',
    'Benimodo',
    'Benissa',
    'Benito',
    'Berja',
    'Bermeo',
    'Betanzos',
    'Bollullos de la Mitación',
    'Bollullos Par del Condado',
    'Borja',
    'Bormujos',
    'Bornos',
    'Botarell',
    'Briviesca',
    'Brunete',
    'Buenavista del Norte',
    'Buñol',
    'Burgos',
    'Burlada',
    'Burmester',
    'Burriana',
    'Cabeza del Buey',
    'Cabezón de la Sal',
    'Cabra',
    'Cadiz',
    'Calañas',
    'Calanda',
    'Calasparra',
    'Calatayud',
    'Calella',
    'Callosa de Segura',
    'Callosa d’En Sarria',
    'Camas',
    'Campo de Criptana',
    'Candelaria',
    'Canet de Berenguer',
    'Canet de Mar',
    'Cañete de las Torres',
    'Cangas de Narcea',
    'Cangas del Narcea',
    'Cañete de las Torres',
    'Canillo',
    'Cantillana',
    'Caravaca de la Cruz',
    'Carballo',
    'Carboneras',
    'Cardedeu',
    'Carmona',
    'Carranque',
    'Carrascosa del Campo',
    'Cartagena',
    'Cártama',
    'Casarabonela',
    'Casarrubuelos',
    'Casares',
    'Caspe',
    'Castril',
    'Castro del Rio',
    'Castro Urdiales',
    'Castrojeriz',
    'Catalonia',
    'Catarroja',
    'Caudete',
    'Cehegin',
    'Ceuta',
    'Cieza',
    'Ciudad Real',
    'Clariana',
    'Cocentaina',
    'Colmenar',
    'Colmenar Viejo',
    'Colmenarejo',
    'Collado Villalba',
    'Conil de la Frontera',
    'Córdoba',
    'Coria del Rio',
    'Coslada',
    'Costitx',
    'Crespos',
    'Cuenca',
    'Cullera',
    'Daimiel',
    'Daimus',
    'Denia',
    'Dos Hermanas',
    'Durango',
    'Ecija',
    'El Astillero',
    'El Boalo',
    'El Campello',
    'El Ejido',
    'El Espinar',
    'El Masnou',
    'El Palmar',
    'El Parador de las Hortichuelas',
    'El Puerto de Santa María',
    'El Rosario',
    'El Saucejo',
    'El Viso del Alcor',
    'Elche',
    'Elda',
    'Elx',
    'Emperador',
    'Encamp',
    'Enix',
    'Ermua',
    'Esparreguera',
    'Espartinas',
    'Esplugues de Llobregat',
    'Estella',
    'Estepona',
    'Etxebarri',
    'Felanitx',
    'Ferrol',
    'Figueres',
    'Firgas',
    'Fisterra',
    'Fitero',
    'Fortuna',
    'Fregenal de la Sierra',
    'Fresno de la Ribera',
    'Frigiliana',
    'Fuengirola',
    'Fuente Alamo de Murcia',
    'Fuenlabrada',
    'Fuentes de Andalucia',
    'Gandia',
    'Garachico',
    'Garrucha',
    'Gava',
    'Gibraltar',
    'Gijon',
    'Girona',
    'Granada',
    'Granja de Rocamora',
    'Guadalajara',
    'Guadalupe',
    'Guadix',
    'Guamasa',
    'Guardo',
    'Guaro',
    'Guardamar del Segura',
    'Guillena',
    'Haro',
    'Hellin',
    'Hernani',
    'Hinojosa del Duque',
    'Horcajo de Santiago',
    'Horcajo de la Sierra',
    'Horcajo de los Montes',
    'Horcajuelo de la Sierra',
    'Huesca',
    'Huelva',
    'Huercal de Almeria',
    'Huercal-Overa',
    'Icod de los Vinos',
    'Iglesuela del Cid',
    'Igualada',
    'Illescas',
    'Illora',
    'Ingenio',
    'Ingles',
    'Irun',
    'Isla Cristina',
    'Isora',
    'Isla Plana',
    'Ituren',
    'Iznajar',
    'Iznatoraf',
    'Jaén',
    'Javea',
    'Jerez de la Frontera',
    'Jijona',
    'Jodar',
    'Jumilla',
    'Jun',
    'La Algaba',
    'La Almunia de Doña Godina',
    'La Antilla',
    'La Coruña',
    'La Frontera',
    'La Gomera',
    'La Lantejuela',
    'La Línea de la Concepción',
    'La Luisiana',
    'La Mata',
    'La Oliva',
    'La Palma del Condado',
    'La Puebla de Almoradiel',
    'La Roda',
    'La Romana',
    'La Solana',
    'La Taha',
    'La Union',
    'La Vall de Uxo',
    'Lanjaron',
    'Laredo',
    'Las Galletas',
    'Las Norias de Daza',
    'Las Palmas de Gran Canaria',
    'Las Rozas de Madrid',
    'Las Torres de Cotillas',
    'Lazkao',
    'Laza',
    'Lebrija',
    'Lekeitio',
    'Leon',
    'Lerma',
    'Linares',
    'Lleida',
    'Loeches',
    'Lora del Rio',
    'Lorcha',
    'Los Alcázares',
    'Los Barrios',
    'Los Corrales',
    'Los Corrales de Buelna',
    'Los Cristianos',
    'Los Llanos de Aridane',
    'Los Monteros',
    'Los Palacios y Villafranca',
    'Los Realejos',
    'Lozoya',
    'Lozoyuela',
    'Lucena',
    'Lugo',
    'Lumbreras',
    'Luque',
    'Madrid',
    'Magan',
    'Mahón',
    'Malaga',
    'Mancha Real',
    'Mancha Vieja',
    'Manises',
    'Manlleu',
    'Playa de Aro',
    'Pobla de Farnals',
    'Pobla de Vallbona',
    'Pobla del Duc',
    'Pocito',
    'Pola de Siero',
    'Pollença',
    'Polop',
    'Pomar de Cinca',
    'Ponteareas',
    'Pontevedra',
    'Poretta',
    'Port de Pollenca',
    'Port de la Selva',
    'Puente Genil',
    'Puertollano',
    'Puerto de la Cruz',
    'Puerto Real',
    'Puigcerda',
    'Pulianas',
    'Quatretonda',
    'Quintana del Pidio',
    'Quintanilla de las Viñas',
    'Rafelbuñol',
    'Rafaela',
    'Ronda',
    'Rojales',
    'Roquetas de Mar',
    'Rosario',
    'Rubí',
    'Salamanca',
    'Salinas',
    'Salou',
    'Salud',
    'San Adrian de Juarros',
    'San Bartolome',
    'San Bartolome de Tirajana',
    'San Esteban de Gormaz',
    'San Fernando',
    'San Francisco',
    'San Javier',
    'San Juan',
    'San Juan de Alicante',
    'San Martin del Tesorillo',
    'San Pedro de Alcántara',
    'San Rafael',
    'San Sebastián',
    'San Vicente del Raspeig',
    'Sanlúcar de Barrameda',
    'Sant Adrià de Besòs',
    'Sant Feliu de Guíxols',
    'Sant Joan Despí',
    'Sant Just Desvern',
    'Sant Quirze del Vallès',
    'Santander',
    'Santillana del Mar',
    'Santiago de Compostela',
    'Santoña',
    'Sarria',
    'Sariñena',
    'Sarria de Ter',
    'Sax',
    'Segovia',
    'Sevilla',
    'Silla',
    'Silla de Albarracín',
    'Sines',
    'Soria',
    'Sotillo de la Adrada',
    'Sotrondio',
    'Talavera de la Reina',
    'Talayuelas',
    'Tarragona',
    'Tarragona',
    'Teguise',
    'Teruel',
    'Teulada',
    'Torre de la Horadada',
    'Torre de Juan Abad',
    'Torre de Moncorvo',
    'Torre Pacheco',
    'Torreblanca',
    'Torrejon de Ardoz',
    'Torreon',
    'Torreperogil',
    'Torrevieja',
    'Torremolinos',
    'Torres de la Alameda',
    'Torrijos',
    'Tortosa',
    'Totana',
    'Trinidad',
    'Tudela',
    'Ubeda',
    'Utrera',
    'Valdemoro',
    'Valencia',
    'Vallehermoso',
    'Vallehermoso',
    'Villanueva de Alcardete',
    'Villanueva de Gállego',
    'Villanueva de la Cañada',
    'Villanueva de la Torre',
    'Villanueva de los Infantes',
    'Villanueva de los Llanos',
    'Villanueva de Perales',
    'Villanueva de la Serena',
    'Villanueva de la Vega',
    'Villanueva de los Angeles',
    'Villarejo de Salvanés',
    'Villarrubia de Santiago',
    'Villaviciosa de Odón',
    'Villaviciosa de Tajuña',
    'Villarrobledo',
    'Vila-real',
    'Vila-Seca',
    'Vinuesa',
    'Viveiro',
    'Xabia',
    'Zaragoza',
    'Zarautz',
    'Zegama',
    'Ziganda',
    'Zizur Mayor',
    'Zumaia',
    'Zurrón'
  ];

List enCities = ['Adeje',
  'Adra',
  'Aguadulce',
  'Alicante',
  'Aguilas',
  'Ajalvir',
  'Alameda',
  'Alcala de Guadaira',
  'Alcala de Henares',
  'Alcala la Real',
  'Alcanar',
  'Alcantarilla',
  'Alcaraz',
  'Alcázar de San Juan',
  'Alcoi',
  'Alcobendas',
  'Alcorcon',
  'Alcoy',
  'Alcudia',
  'Aldaia',
  'Alfafar',
  'Algeciras',
  'Algemesi',
  'Alhaurin de la Torre',
  'Alhaurin el Grande',
  'Alhama de Murcia',
  'Aljaraque',
  'Almagro',
  'Almanza',
  'Almazora',
  'Almensilla',
  'Almonte',
  'Almoradi',
  'Almunecar',
  'Alozaina',
  'Alpedrete',
  'Altura',
  'Alzira',
  'Amorebieta',
  'Amposta',
  'Anchuelo',
  'Andorra',
  'Andujar',
  'Anguiano',
  'Antigua',
  'Aranda de Duero',
  'Aranjuez',
  'Archena',
  'Arcos de la Frontera',
  'Arganda del Rey',
  'Arges',
  'Arinaga',
  'Arona',
  'Arrecife',
  'Arriate',
  'Arroyo de la Miel',
  'Astorga',
  'Avila',
  'Aviles',
  'Azpeitia',
  'Baeza',
  'Bailen',
  'Balaguer',
  'Baños de la Encina',
  'Barbastro',
  'Barcelona',
  'Barreiros',
  'Baza',
  'Beas de Granada',
  'Beas de Segura',
  'Begues',
  'Benasal',
  'Benicarlo',
  'Benidorm',
  'Benifaio',
  'Benijofar',
  'Benimodo',
  'Benissa',
  'Benito',
  'Berja',
  'Bermeo',
  'Betanzos',
  'Bollullos de la Mitación',
  'Bollullos Par del Condado',
  'Borja',
  'Bormujos',
  'Bornos',
  'Botarell',
  'Briviesca',
  'Brunete',
  'Buenavista del Norte',
  'Buñol',
  'Burgos',
  'Burlada',
  'Burmester',
  'Burriana',
  'Cabeza del Buey',
  'Cabezón de la Sal',
  'Cabra',
  'Cadiz',
  'Calañas',
  'Calanda',
  'Calasparra',
  'Calatayud',
  'Calella',
  'Callosa de Segura',
  'Callosa d’En Sarria',
  'Camas',
  'Campo de Criptana',
  'Candelaria',
  'Canet de Berenguer',
  'Canet de Mar',
  'Cañete de las Torres',
  'Cangas de Narcea',
  'Cangas del Narcea',
  'Cañete de las Torres',
  'Canillo',
  'Cantillana',
  'Caravaca de la Cruz',
  'Carballo',
  'Carboneras',
  'Cardedeu',
  'Carmona',
  'Carranque',
  'Carrascosa del Campo',
  'Cartagena',
  'Cártama',
  'Casarabonela',
  'Casarrubuelos',
  'Casares',
  'Caspe',
  'Castril',
  'Castro del Rio',
  'Castro Urdiales',
  'Castrojeriz',
  'Catalonia',
  'Catarroja',
  'Caudete',
  'Cehegin',
  'Ceuta',
  'Cieza',
  'Ciudad Real',
  'Clariana',
  'Cocentaina',
  'Colmenar',
  'Colmenar Viejo',
  'Colmenarejo',
  'Collado Villalba',
  'Conil de la Frontera',
  'Córdoba',
  'Coria del Rio',
  'Coslada',
  'Costitx',
  'Crespos',
  'Cuenca',
  'Cullera',
  'Daimiel',
  'Daimus',
  'Denia',
  'Dos Hermanas',
  'Durango',
  'Ecija',
  'El Astillero',
  'El Boalo',
  'El Campello',
  'El Ejido',
  'El Espinar',
  'El Masnou',
  'El Palmar',
  'El Parador de las Hortichuelas',
  'El Puerto de Santa María',
  'El Rosario',
  'El Saucejo',
  'El Viso del Alcor',
  'Elche',
  'Elda',
  'Elx',
  'Emperador',
  'Encamp',
  'Enix',
  'Ermua',
  'Esparreguera',
  'Espartinas',
  'Esplugues de Llobregat',
  'Estella',
  'Estepona',
  'Etxebarri',
  'Felanitx',
  'Ferrol',
  'Figueres',
  'Firgas',
  'Fisterra',
  'Fitero',
  'Fortuna',
  'Fregenal de la Sierra',
  'Fresno de la Ribera',
  'Frigiliana',
  'Fuengirola',
  'Fuente Alamo de Murcia',
  'Fuenlabrada',
  'Fuentes de Andalucia',
  'Gandia',
  'Garachico',
  'Garrucha',
  'Gava',
  'Gibraltar',
  'Gijon',
  'Girona',
  'Granada',
  'Granja de Rocamora',
  'Guadalajara',
  'Guadalupe',
  'Guadix',
  'Guamasa',
  'Guardo',
  'Guaro',
  'Guardamar del Segura',
  'Guillena',
  'Haro',
  'Hellin',
  'Hernani',
  'Hinojosa del Duque',
  'Horcajo de Santiago',
  'Horcajo de la Sierra',
  'Horcajo de los Montes',
  'Horcajuelo de la Sierra',
  'Huesca',
  'Huelva',
  'Huercal de Almeria',
  'Huercal-Overa',
  'Icod de los Vinos',
  'Iglesuela del Cid',
  'Igualada',
  'Illescas',
  'Illora',
  'Ingenio',
  'Ingles',
  'Irun',
  'Isla Cristina',
  'Isora',
  'Isla Plana',
  'Ituren',
  'Iznajar',
  'Iznatoraf',
  'Jaén',
  'Javea',
  'Jerez de la Frontera',
  'Jijona',
  'Jodar',
  'Jumilla',
  'Jun',
  'La Algaba',
  'La Almunia de Doña Godina',
  'La Antilla',
  'La Coruña',
  'La Frontera',
  'La Gomera',
  'La Lantejuela',
  'La Línea de la Concepción',
  'La Luisiana',
  'La Mata',
  'La Oliva',
  'La Palma del Condado',
  'La Puebla de Almoradiel',
  'La Roda',
  'La Romana',
  'La Solana',
  'La Taha',
  'La Union',
  'La Vall de Uxo',
  'Lanjaron',
  'Laredo',
  'Las Galletas',
  'Las Norias de Daza',
  'Las Palmas de Gran Canaria',
  'Las Rozas de Madrid',
  'Las Torres de Cotillas',
  'Lazkao',
  'Laza',
  'Lebrija',
  'Lekeitio',
  'Leon',
  'Lerma',
  'Linares',
  'Lleida',
  'Loeches',
  'Lora del Rio',
  'Lorcha',
  'Los Alcázares',
  'Los Barrios',
  'Los Corrales',
  'Los Corrales de Buelna',
  'Los Cristianos',
  'Los Llanos de Aridane',
  'Los Monteros',
  'Los Palacios y Villafranca',
  'Los Realejos',
  'Lozoya',
  'Lozoyuela',
  'Lucena',
  'Lugo',
  'Lumbreras',
  'Luque',
  'Madrid',
  'Magan',
  'Mahón',
  'Malaga',
  'Mancha Real',
  'Mancha Vieja',
  'Manises',
  'Manlleu',
  'Playa de Aro',
  'Pobla de Farnals',
  'Pobla de Vallbona',
  'Pobla del Duc',
  'Pocito',
  'Pola de Siero',
  'Pollença',
  'Polop',
  'Pomar de Cinca',
  'Ponteareas',
  'Pontevedra',
  'Poretta',
  'Port de Pollenca',
  'Port de la Selva',
  'Puente Genil',
  'Puertollano',
  'Puerto de la Cruz',
  'Puerto Real',
  'Puigcerda',
  'Pulianas',
  'Quatretonda',
  'Quintana del Pidio',
  'Quintanilla de las Viñas',
  'Rafelbuñol',
  'Rafaela',
  'Ronda',
  'Rojales',
  'Roquetas de Mar',
  'Rosario',
  'Rubí',
  'Salamanca',
  'Salinas',
  'Salou',
  'Salud',
  'San Adrian de Juarros',
  'San Bartolome',
  'San Bartolome de Tirajana',
  'San Esteban de Gormaz',
  'San Fernando',
  'San Francisco',
  'San Javier',
  'San Juan',
  'San Juan de Alicante',
  'San Martin del Tesorillo',
  'San Pedro de Alcántara',
  'San Rafael',
  'San Sebastián',
  'San Vicente del Raspeig',
  'Sanlúcar de Barrameda',
  'Sant Adrià de Besòs',
  'Sant Feliu de Guíxols',
  'Sant Joan Despí',
  'Sant Just Desvern',
  'Sant Quirze del Vallès',
  'Santander',
  'Santillana del Mar',
  'Santiago de Compostela',
  'Santoña',
  'Sarria',
  'Sariñena',
  'Sarria de Ter',
  'Sax',
  'Segovia',
  'Sevilla',
  'Silla',
  'Silla de Albarracín',
  'Sines',
  'Soria',
  'Sotillo de la Adrada',
  'Sotrondio',
  'Talavera de la Reina',
  'Talayuelas',
  'Tarragona',
  'Tarragona',
  'Teguise',
  'Teruel',
  'Toledo',
  'Tomares',
  'Tordera',
  'Torrejon de Ardoz',
  'Torrejon de Velasco',
  'Torre del Mar',
  'Torre la Vega',
  'Torrijos',
  'Tortosa',
  'Torreblanca',
  'Torreblanca de Aragón',
  'Torrelavega',
  'Torreón',
  'Torreón',
  'Torreón de la Victoria',
  'Torremolinos',
  'Torres de la Alameda',
  'Torrevaqueros',
  'Torreón de Aracena',
  'Toro',
  'Totana',
  'Trujillo',
  'Tudela',
  'Tuy',
  'Ubrique',
  'Ugena',
  'Ullastret',
  'Unquera',
  'Valencia',
  'Valdepeñas',
  'Valdemoro',
  'Vallehermoso',
  'Vallehermoso',
  'Valverde',
  'Valverde del Camino',
  'Valladolid',
  'Vall d’Uixó',
  'Valls',
  'Vallirana',
  'Villadangos del Páramo',
  'Villanueva de la Cañada',
  'Villanueva de la Serena',
  'Villanueva de los Infantes',
  'Villarejo de Salvanés',
  'Villanueva del Pardillo',
  'Villanueva del Río y Minas',
  'Villarrubia de los Ojos',
  'Villaverde',
  'Vila-real',
  'Vila de Gràcia',
  'Vilafamés',
  'Vilalba',
  'Vilafranca del Penedès',
  'Vila-real',
  'Vilanova i la Geltrú',
  'Vistabella del Maestre',
  'Xàtiva',
  'Yunquera',
  'Zafra',
  'Zahara de los Atunes',
  'Zahara de la Sierra',
  'Zaragoza',
  'Zaragoza',
  'Zegama',
  'Zorita del Maestre',
  'Zumaia',
  'Zurgena',
];



List idSpainsCities = [];

List translations = [
  {'name_ru': 'Адхе', 'name_en': 'Adeje', 'name_sp': 'Adeje'},
  {'name_ru': 'Адра', 'name_en': 'Adra', 'name_sp': 'Adra'},
  {'name_ru': 'Агуадульсе', 'name_en': 'Aguadulce', 'name_sp': 'Aguadulce'},
  {'name_ru': 'Аликанте', 'name_en': 'Alicante', 'name_sp': 'Alicante'},
  {'name_ru': 'Агилас', 'name_en': 'Águilas', 'name_sp': 'Águilas'},
  {'name_ru': 'Ахальвир', 'name_en': 'Ajalvir', 'name_sp': 'Ajalvir'},
  {'name_ru': 'Альменда', 'name_en': 'Alameda', 'name_sp': 'Alameda'},
  {
    'name_ru': 'Алькала-де-Гвадаира',
    'name_en': 'Alcalá de Guadaíra',
    'name_sp': 'Alcalá de Guadaíra'
  },
  {
    'name_ru': 'Алькала-де-Энарес',
    'name_en': 'Alcalá de Henares',
    'name_sp': 'Alcalá de Henares'
  },
  {
    'name_ru': 'Алькала-ла-Реаль',
    'name_en': 'Alcalá la Real',
    'name_sp': 'Alcalá la Real'
  },
  {'name_ru': 'Алканар', 'name_en': 'Alcanar', 'name_sp': 'Alcanar'},
  {
    'name_ru': 'Алкантари́лья',
    'name_en': 'Alcantarilla',
    'name_sp': 'Alcantarilla'
  },
  {'name_ru': 'Алькарас', 'name_en': 'Alcaraz', 'name_sp': 'Alcaraz'},
  {
    'name_ru': 'Алькасар-де-Сан-Хуан',
    'name_en': 'Alcázar de San Juan',
    'name_sp': 'Alcázar de San Juan'
  },
  {'name_ru': 'Алькои', 'name_en': 'Alcoi', 'name_sp': 'Alcoi'},
  {'name_ru': 'Алкобендас', 'name_en': 'Alcobendas', 'name_sp': 'Alcobendas'},
  {'name_ru': 'Алккоркон', 'name_en': 'Alcorcón', 'name_sp': 'Alcorcón'},
  {'name_ru': 'Алкой', 'name_en': 'Alcoy', 'name_sp': 'Alcoy'},
  {'name_ru': 'Алкудия', 'name_en': 'Alcudia', 'name_sp': 'Alcudia'},
  {'name_ru': 'Альда́йа', 'name_en': 'Aldaia', 'name_sp': 'Aldaia'},
  {'name_ru': 'Альфафар', 'name_en': 'Alfafar', 'name_sp': 'Alfafar'},
  {'name_ru': 'Алхеси́рас', 'name_en': 'Algeciras', 'name_sp': 'Algeciras'},
  {'name_ru': 'Алхемеси', 'name_en': 'Algemesí', 'name_sp': 'Algemesí'},
  {
    'name_ru': 'Альхаурин-де-ла-Торре',
    'name_en': 'Alhaurín de la Torre',
    'name_sp': 'Alhaurín de la Torre'
  },
  {
    'name_ru': 'Альхаурин-эль-Гранде',
    'name_en': 'Alhaurín el Grande',
    'name_sp': 'Alhaurín el Grande'
  },
  {
    'name_ru': 'Альхама-де-Мурсия',
    'name_en': 'Alhama de Murcia',
    'name_sp': 'Alhama de Murcia'
  },
  {'name_ru': 'Альхарак', 'name_en': 'Aljaraque', 'name_sp': 'Aljaraque'},
  {'name_ru': 'Алмагро', 'name_en': 'Almagro', 'name_sp': 'Almagro'},
  {'name_ru': 'Альманса', 'name_en': 'Almansa', 'name_sp': 'Almansa'},
  {'name_ru': 'Алмазора', 'name_en': 'Almazora', 'name_sp': 'Almazora'},
  {'name_ru': 'Альменсилья', 'name_en': 'Almensilla', 'name_sp': 'Almensilla'},
  {'name_ru': 'Альмонт', 'name_en': 'Almonte', 'name_sp': 'Almonte'},
  {'name_ru': 'Альморади', 'name_en': 'Almoradí', 'name_sp': 'Almoradí'},
  {'name_ru': 'Альмуньекар', 'name_en': 'Almuñécar', 'name_sp': 'Almuñécar'},
  {'name_ru': 'Алосайна', 'name_en': 'Alozaina', 'name_sp': 'Alozaina'},
  {'name_ru': 'Альпедрете', 'name_en': 'Alpedrete', 'name_sp': 'Alpedrete'},
  {'name_ru': 'Альтура', 'name_en': 'Altura', 'name_sp': 'Altura'},
  {'name_ru': 'Альцира', 'name_en': 'Alzira', 'name_sp': 'Alzira'},
  {'name_ru': 'Аморебьета', 'name_en': 'Amorebieta', 'name_sp': 'Amorebieta'},
  {'name_ru': 'Ампоста', 'name_en': 'Amposta', 'name_sp': 'Amposta'},
  {'name_ru': 'Анхунело', 'name_en': 'Anchuelo', 'name_sp': 'Anchuelo'},
  {'name_ru': 'Андорра', 'name_en': 'Andorra', 'name_sp': 'Andorra'},
  {'name_ru': 'Андужар', 'name_en': 'Andújar', 'name_sp': 'Andújar'},
  {'name_ru': 'Ангиано', 'name_en': 'Anguiano', 'name_sp': 'Anguiano'},
  {'name_ru': 'Антигва', 'name_en': 'Antigua', 'name_sp': 'Antigua'},
  {
    'name_ru': 'Аранда-де-Дуэро',
    'name_en': 'Aranda de Duero',
    'name_sp': 'Aranda de Duero'
  },
  {'name_ru': 'Аранхуэс', 'name_en': 'Aranjuez', 'name_sp': 'Aranjuez'},
  {'name_ru': 'Архена', 'name_en': 'Archena', 'name_sp': 'Archena'},
  {
    'name_ru': 'Аркос-де-ла-Фронтера',
    'name_en': 'Arcos de la Frontera',
    'name_sp': 'Arcos de la Frontera'
  },
  {
    'name_ru': 'Арганда-дель-Rey',
    'name_en': 'Arganda del Rey',
    'name_sp': 'Arganda del Rey'
  },
  {'name_ru': 'Архес', 'name_en': 'Arges', 'name_sp': 'Arges'},
  {'name_ru': 'Аринага', 'name_en': 'Arinaga', 'name_sp': 'Arinaga'},
  {'name_ru': 'Арона', 'name_en': 'Arona', 'name_sp': 'Arona'},
  {'name_ru': 'Арресифе', 'name_en': 'Arrecife', 'name_sp': 'Arrecife'},
  {'name_ru': 'Арриате', 'name_en': 'Arriate', 'name_sp': 'Arriate'},
  {
    'name_ru': 'Арройо-де-ла-Миль',
    'name_en': 'Arroyo de la Miel',
    'name_sp': 'Arroyo de la Miel'
  },
  {'name_ru': 'Асторга', 'name_en': 'Astorga', 'name_sp': 'Astorga'},
  {'name_ru': 'Авила', 'name_en': 'Ávila', 'name_sp': 'Ávila'},
  {'name_ru': 'Авилес', 'name_en': 'Avilés', 'name_sp': 'Avilés'},
  {'name_ru': 'Аспеция', 'name_en': 'Azpeitia', 'name_sp': 'Azpeitia'},
  {'name_ru': 'Бэса', 'name_en': 'Baeza', 'name_sp': 'Baeza'},
  {'name_ru': 'Байлен', 'name_en': 'Bailén', 'name_sp': 'Bailén'},
  {'name_ru': 'Балагер', 'name_en': 'Balaguer', 'name_sp': 'Balaguer'},
  {
    'name_ru': 'Банос-де-ла-Энсина',
    'name_en': 'Baños de la Encina',
    'name_sp': 'Baños de la Encina'
  },
  {'name_ru': 'Барбастро', 'name_en': 'Barbastro', 'name_sp': 'Barbastro'},
  {'name_ru': 'Барселона', 'name_en': 'Barcelona', 'name_sp': 'Barcelona'},
  {'name_ru': 'Баррейрос', 'name_en': 'Barreiros', 'name_sp': 'Barreiros'},
  {'name_ru': 'База', 'name_en': 'Baza', 'name_sp': 'Baza'},
  {
    'name_ru': 'Беас-де-Гранада',
    'name_en': 'Beas de Granada',
    'name_sp': 'Beas de Granada'
  },
  {
    'name_ru': 'Беас-де-Сегура',
    'name_en': 'Beas de Segura',
    'name_sp': 'Beas de Segura'
  },
  {'name_ru': 'Бегес', 'name_en': 'Begues', 'name_sp': 'Begues'},
  {'name_ru': 'Бенасаль', 'name_en': 'Benasal', 'name_sp': 'Benasal'},
  {'name_ru': 'Беникарло', 'name_en': 'Benicarló', 'name_sp': 'Benicarló'},
  {'name_ru': 'Бенидорм', 'name_en': 'Benidorm', 'name_sp': 'Benidorm'},
  {'name_ru': 'Бенифайо', 'name_en': 'Benifaió', 'name_sp': 'Benifaió'},
  {'name_ru': 'Бенихофар', 'name_en': 'Benijófar', 'name_sp': 'Benijófar'},
  {'name_ru': 'Бенимодо', 'name_en': 'Benimodo', 'name_sp': 'Benimodo'},
  {'name_ru': 'Бенисса', 'name_en': 'Benissa', 'name_sp': 'Benissa'},
  {'name_ru': 'Бенито', 'name_en': 'Benito', 'name_sp': 'Benito'},
  {'name_ru': 'Берха', 'name_en': 'Berja', 'name_sp': 'Berja'},
  {'name_ru': 'Бермео', 'name_en': 'Bermeo', 'name_sp': 'Bermeo'},
  {'name_ru': 'Бетанзос', 'name_en': 'Betanzos', 'name_sp': 'Betanzos'},
  {
    'name_ru': 'Боллюльос-де-ла-Митасьон',
    'name_en': 'Bollullos de la Mitación',
    'name_sp': 'Bollullos de la Mitación'
  },
  {
    'name_ru': 'Боллюльос-пар-дель-Кондадо',
    'name_en': 'Bollullos Par del Condado',
    'name_sp': 'Bollullos Par del Condado'
  },
  {'name_ru': 'Борха', 'name_en': 'Borja', 'name_sp': 'Borja'},
  {'name_ru': 'Бормухос', 'name_en': 'Bormujos', 'name_sp': 'Bormujos'},
  {'name_ru': 'Борнос', 'name_en': 'Bornos', 'name_sp': 'Bornos'},
  {'name_ru': 'Ботарель', 'name_en': 'Botarell', 'name_sp': 'Botarell'},
  {'name_ru': 'Бривьеска', 'name_en': 'Briviesca', 'name_sp': 'Briviesca'},
  {'name_ru': 'Брунете', 'name_en': 'Brunete', 'name_sp': 'Brunete'},
  {
    'name_ru': 'Буэна Vista del Norte',
    'name_en': 'Buenavista del Norte',
    'name_sp': 'Buenavista del Norte'
  },
  {'name_ru': 'Буньол', 'name_en': 'Bunol', 'name_sp': 'Buñol'},
  {'name_ru': 'Бургос', 'name_en': 'Burgos', 'name_sp': 'Burgos'},
  {'name_ru': 'Бурлада', 'name_en': 'Burlada', 'name_sp': 'Burlada'},
  {'name_ru': 'Бурместер', 'name_en': 'Burmester', 'name_sp': 'Burmester'},
  {'name_ru': 'Бурриана', 'name_en': 'Burriana', 'name_sp': 'Burriana'},
  {
    'name_ru': 'Голова Быка',
    'name_en': 'Cabeza del Buey',
    'name_sp': 'Cabeza del Buey'
  },
  {
    'name_ru': 'Кабесон-де-ла-Саль',
    'name_en': 'Cabezón de la Sal',
    'name_sp': 'Cabezón de la Sal'
  },
  {'name_ru': 'Кабра', 'name_en': 'Cabra', 'name_sp': 'Cabra'},
  {'name_ru': 'Кадис', 'name_en': 'Cádiz', 'name_sp': 'Cádiz'},
  {'name_ru': 'Калаñas', 'name_en': 'Calañas', 'name_sp': 'Calañas'},
  {'name_ru': 'Каланда', 'name_en': 'Calanda', 'name_sp': 'Calanda'},
  {'name_ru': 'Каласпарра', 'name_en': 'Calasparra', 'name_sp': 'Calasparra'},
  {'name_ru': 'Калатаюд', 'name_en': 'Calatayud', 'name_sp': 'Calatayud'},
  {'name_ru': 'Калелья', 'name_en': 'Calella', 'name_sp': 'Calella'},
  {
    'name_ru': 'Кальоса-де-Сегура',
    'name_en': 'Callosa de Segura',
    'name_sp': 'Callosa de Segura'
  },
  {
    'name_ru': 'Кальоса-д’Эн-Саррия',
    'name_en': 'Callosa d’En Sarria',
    'name_sp': 'Callosa d’En Sarria'
  },
  {'name_ru': 'Камас', 'name_en': 'Camas', 'name_sp': 'Camas'},
  {
    'name_ru': 'Кампус-де-Криптана',
    'name_en': 'Campo de Criptana',
    'name_sp': 'Campo de Criptana'
  },
  {'name_ru': 'Канделярия', 'name_en': 'Candelaria', 'name_sp': 'Candelaria'},
  {
    'name_ru': 'Канет-де-Берегуэр',
    'name_en': 'Canet de Berenguer',
    'name_sp': 'Canet de Berenguer'
  },
  {
    'name_ru': 'Канет-де-Мар',
    'name_en': 'Canet de Mar',
    'name_sp': 'Canet de Mar'
  },
  {
    'name_ru': 'Канета-де-лас-Торрес',
    'name_en': 'Cañete de las Torres',
    'name_sp': 'Cañete de las Torres'
  },
  {
    'name_ru': 'Канхас-де-Нарсеа',
    'name_en': 'Cangas de Narcea',
    'name_sp': 'Cangas de Narcea'
  },
  {
    'name_ru': 'Канхас-дель-Нарсеа',
    'name_en': 'Cangas del Narcea',
    'name_sp': 'Cangas del Narcea'
  },
  {
    'name_ru': 'Канета-де-лас-Торрес',
    'name_en': 'Cañete de las Torres',
    'name_sp': 'Cañete de las Torres'
  },
  {'name_ru': 'Канильо', 'name_en': 'Canillo', 'name_sp': 'Canillo'},
  {'name_ru': 'Кантильяна', 'name_en': 'Cantillana', 'name_sp': 'Cantillana'},
  {
    'name_ru': 'Каравака-де-ла-Крус',
    'name_en': 'Caravaca de la Cruz',
    'name_sp': 'Caravaca de la Cruz'
  },
  {'name_ru': 'Карбальо', 'name_en': 'Carballo', 'name_sp': 'Carballo'},
  {'name_ru': 'Карбонерас', 'name_en': 'Carboneras', 'name_sp': 'Carboneras'},
  {'name_ru': 'Кардеду', 'name_en': 'Cardedeu', 'name_sp': 'Cardedeu'},
  {'name_ru': 'Кармона', 'name_en': 'Carmona', 'name_sp': 'Carmona'},
  {'name_ru': 'Каранке', 'name_en': 'Carranque', 'name_sp': 'Carranque'},
  {
    'name_ru': 'Караскоса-дель-Кампо',
    'name_en': 'Carrascosa del Campo',
    'name_sp': 'Carrascosa del Campo'
  },
  {'name_ru': 'Картатена', 'name_en': 'Cartagena', 'name_sp': 'Cartagena'},
  {'name_ru': 'Картама', 'name_en': 'Cártama', 'name_sp': 'Cártama'},
  {
    'name_ru': 'Касарабонела',
    'name_en': 'Casarabonela',
    'name_sp': 'Casarabonela'
  },
  {
    'name_ru': 'Касаррубуэлас',
    'name_en': 'Casarrubuelos',
    'name_sp': 'Casarrubuelos'
  },
  {'name_ru': 'Касарес', 'name_en': 'Casares', 'name_sp': 'Casares'},
  {'name_ru': 'Каспе', 'name_en': 'Caspe', 'name_sp': 'Caspe'},
  {'name_ru': 'Кастрил', 'name_en': 'Castril', 'name_sp': 'Castril'},
  {
    'name_ru': 'Кастро-дель-Рио',
    'name_en': 'Castro del Rio',
    'name_sp': 'Castro del Rio'
  },
  {
    'name_ru': 'Кастро-Урдялес',
    'name_en': 'Castro Urdiales',
    'name_sp': 'Castro Urdiales'
  },
  {
    'name_ru': 'Кастрохериз',
    'name_en': 'Castrojeriz',
    'name_sp': 'Castrojeriz'
  },
  {'name_ru': 'Каталония', 'name_en': 'Catalonia', 'name_sp': 'Catalonia'},
  {'name_ru': 'Катарроха', 'name_en': 'Catarroja', 'name_sp': 'Catarroja'},
  {'name_ru': 'Кодете', 'name_en': 'Caudete', 'name_sp': 'Caudete'},
  {'name_ru': 'Сеегин', 'name_en': 'Cehegin', 'name_sp': 'Cehegin'},
  {'name_ru': 'Сеута', 'name_en': 'Ceuta', 'name_sp': 'Ceuta'},
  {'name_ru': 'Сьеса', 'name_en': 'Cieza', 'name_sp': 'Cieza'},
  {
    'name_ru': 'Сьюдад-Реал',
    'name_en': 'Ciudad Real',
    'name_sp': 'Ciudad Real'
  },
  {'name_ru': 'Кларьяна', 'name_en': 'Clariana', 'name_sp': 'Clariana'},
  {'name_ru': 'Кокентайна', 'name_en': 'Cocentaina', 'name_sp': 'Cocentaina'},
  {'name_ru': 'Кольменар', 'name_en': 'Colmenar', 'name_sp': 'Colmenar'},
  {
    'name_ru': 'Кольменар-Вьехо',
    'name_en': 'Colmenar Viejo',
    'name_sp': 'Colmenar Viejo'
  },
  {
    'name_ru': 'Кольменарехо',
    'name_en': 'Colmenarejo',
    'name_sp': 'Colmenarejo'
  },
  {
    'name_ru': 'Кольядо-Вильялба',
    'name_en': 'Collado Villalba',
    'name_sp': 'Collado Villalba'
  },
  {
    'name_ru': 'Кониль-де-ла-Фронтера',
    'name_en': 'Conil de la Frontera',
    'name_sp': 'Conil de la Frontera'
  },
  {'name_ru': 'Кордоба', 'name_en': 'Córdoba', 'name_sp': 'Córdoba'},
  {
    'name_ru': 'Кория-дель-Рио',
    'name_en': 'Coria del Rio',
    'name_sp': 'Coria del Rio'
  },
  {'name_ru': 'Кослада', 'name_en': 'Coslada', 'name_sp': 'Coslada'},
  {'name_ru': 'Коститк', 'name_en': 'Costitx', 'name_sp': 'Costitx'},
  {'name_ru': 'Креспос', 'name_en': 'Crespos', 'name_sp': 'Crespos'},
  {'name_ru': 'Куэнка', 'name_en': 'Cuenca', 'name_sp': 'Cuenca'},
  {'name_ru': 'Кульера', 'name_en': 'Cullera', 'name_sp': 'Cullera'},
  {'name_ru': 'Даймель', 'name_en': 'Daimiel', 'name_sp': 'Daimiel'},
  {'name_ru': 'Даймус', 'name_en': 'Daimus', 'name_sp': 'Daimus'},
  {'name_ru': 'Дения', 'name_en': 'Denia', 'name_sp': 'Denia'},
  {
    'name_ru': 'Дос-Эрманас',
    'name_en': 'Dos Hermanas',
    'name_sp': 'Dos Hermanas'
  },
  {'name_ru': 'Дураго', 'name_en': 'Durango', 'name_sp': 'Durango'},
  {'name_ru': 'Эсиха', 'name_en': 'Ecija', 'name_sp': 'Ecija'},
  {
    'name_ru': 'Эль-Астильеро',
    'name_en': 'El Astillero',
    'name_sp': 'El Astillero'
  },
  {'name_ru': 'Эль-Боало', 'name_en': 'El Boalo', 'name_sp': 'El Boalo'},
  {
    'name_ru': 'Эль-Кампельо',
    'name_en': 'El Campello',
    'name_sp': 'El Campello'
  },
  {'name_ru': 'Эль-Эхидо', 'name_en': 'El Ejido', 'name_sp': 'El Ejido'},
  {'name_ru': 'Эль-Эспинар', 'name_en': 'El Espinar', 'name_sp': 'El Espinar'},
  {'name_ru': 'Эль-Масноу', 'name_en': 'El Masnou', 'name_sp': 'El Masnou'},
  {'name_ru': 'Эль-Пальмар', 'name_en': 'El Palmar', 'name_sp': 'El Palmar'},
  {
    'name_ru': 'Эль-Парадор-де-лас-Ортихuelas',
    'name_en': 'El Parador de las Hortichuelas',
    'name_sp': 'El Parador de las Hortichuelas'
  },
  {
    'name_ru': 'Эль-Пуэрто-де-Санта-Мария',
    'name_en': 'El Puerto de Santa María',
    'name_sp': 'El Puerto de Santa María'
  },
  {'name_ru': 'Эль-Росарио', 'name_en': 'El Rosario', 'name_sp': 'El Rosario'},
  {'name_ru': 'Эль-Саусехо', 'name_en': 'El Saucejo', 'name_sp': 'El Saucejo'},
  {
    'name_ru': 'Эль-Висо-дель-Алькор',
    'name_en': 'El Viso del Alcor',
    'name_sp': 'El Viso del Alcor'
  },
  {'name_ru': 'Эльче', 'name_en': 'Elche', 'name_sp': 'Elche'},
  {'name_ru': 'Эльда', 'name_en': 'Elda', 'name_sp': 'Elda'},
  {'name_ru': 'Эльч', 'name_en': 'Elx', 'name_sp': 'Elx'},
  {'name_ru': 'Эмпердор', 'name_en': 'Emperador', 'name_sp': 'Emperador'},
  {'name_ru': 'Энкамп', 'name_en': 'Encamp', 'name_sp': 'Encamp'},
  {'name_ru': 'Эникс', 'name_en': 'Enix', 'name_sp': 'Enix'},
  {'name_ru': 'Эрму', 'name_en': 'Ermua', 'name_sp': 'Ermua'},
  {
    'name_ru': 'Эспаррегера',
    'name_en': 'Esparreguera',
    'name_sp': 'Esparreguera'
  },
  {'name_ru': 'Эспартинес', 'name_en': 'Espartinas', 'name_sp': 'Espartinas'},
  {
    'name_ru': 'Эсплугес-де-Льобрегат',
    'name_en': 'Esplugues de Llobregat',
    'name_sp': 'Esplugues de Llobregat'
  },
  {'name_ru': 'Эстелла', 'name_en': 'Estella', 'name_sp': 'Estella'},
  {'name_ru': 'Эстепона', 'name_en': 'Estepona', 'name_sp': 'Estepona'},
  {'name_ru': 'Эчебарри', 'name_en': 'Etxebarri', 'name_sp': 'Etxebarri'},
  {'name_ru': 'Феланиткс', 'name_en': 'Felanitx', 'name_sp': 'Felanitx'},
  {'name_ru': 'Ферроль', 'name_en': 'Ferrol', 'name_sp': 'Ferrol'},
  {'name_ru': 'Фигерас', 'name_en': 'Figueres', 'name_sp': 'Figueres'},
  {'name_ru': 'Фиргас', 'name_en': 'Firgas', 'name_sp': 'Firgas'},
  {'name_ru': 'Фистерра', 'name_en': 'Fisterra', 'name_sp': 'Fisterra'},
  {'name_ru': 'Фитеро', 'name_en': 'Fitero', 'name_sp': 'Fitero'},
  {'name_ru': 'Фортуна', 'name_en': 'Fortuna', 'name_sp': 'Fortuna'},
  {
    'name_ru': 'Фреганаль-де-ла-Сьерра',
    'name_en': 'Fregenal de la Sierra',
    'name_sp': 'Fregenal de la Sierra'
  },
  {
    'name_ru': 'Фресно-де-ла-Рибера',
    'name_en': 'Fresno de la Ribera',
    'name_sp': 'Fresno de la Ribera'
  },
  {'name_ru': 'Фригилиана', 'name_en': 'Frigiliana', 'name_sp': 'Frigiliana'},
  {'name_ru': 'Фуэнгирола', 'name_en': 'Fuengirola', 'name_sp': 'Fuengirola'},
  {
    'name_ru': 'Фуэнт-аль-Альмо-де-Мурсия',
    'name_en': 'Fuente Alamo de Murcia',
    'name_sp': 'Fuente Alamo de Murcia'
  },
  {
    'name_ru': 'Фуэнлабрада',
    'name_en': 'Fuenlabrada',
    'name_sp': 'Fuenlabrada'
  },
  {
    'name_ru': 'Фуэнтес-де-Анда́лусия',
    'name_en': 'Fuentes de Andalucia',
    'name_sp': 'Fuentes de Andalucia'
  },
  {'name_ru': 'Гандия', 'name_en': 'Gandia', 'name_sp': 'Gandia'},
  {'name_ru': 'Гарачико', 'name_en': 'Garachico', 'name_sp': 'Garachico'},
  {'name_ru': 'Гарруча', 'name_en': 'Garrucha', 'name_sp': 'Garrucha'},
  {'name_ru': 'Гава', 'name_en': 'Gava', 'name_sp': 'Gava'},
  {'name_ru': 'Гибралтар', 'name_en': 'Gibraltar', 'name_sp': 'Gibraltar'},
  {'name_ru': 'Хихон', 'name_en': 'Gijon', 'name_sp': 'Gijon'},
  {'name_ru': 'Жирона', 'name_en': 'Girona', 'name_sp': 'Girona'},
  {'name_ru': 'Гранада', 'name_en': 'Granada', 'name_sp': 'Granada'},
  {
    'name_ru': 'Гранха-де-Рокамора',
    'name_en': 'Granja de Rocamora',
    'name_sp': 'Granja de Rocamora'
  },
  {
    'name_ru': 'Гвадалахара',
    'name_en': 'Guadalajara',
    'name_sp': 'Guadalajara'
  },
  {'name_ru': 'Гвадупе', 'name_en': 'Guadalupe', 'name_sp': 'Guadalupe'},
  {'name_ru': 'Гуадакс', 'name_en': 'Guadix', 'name_sp': 'Guadix'},
  {'name_ru': 'Гуамаса', 'name_en': 'Guamasa', 'name_sp': 'Guamasa'},
  {'name_ru': 'Гуардо', 'name_en': 'Guardo', 'name_sp': 'Guardo'},
  {'name_ru': 'Гуаро', 'name_en': 'Guaro', 'name_sp': 'Guaro'},
  {
    'name_ru': 'Гуардамар-дель-Сегура',
    'name_en': 'Guardamar del Segura',
    'name_sp': 'Guardamar del Segura'
  },
  {'name_ru': 'Гуильена', 'name_en': 'Guillena', 'name_sp': 'Guillena'},
  {'name_ru': 'Харо', 'name_en': 'Haro', 'name_sp': 'Haro'},
  {'name_ru': 'Эль-Хеллин', 'name_en': 'Hellin', 'name_sp': 'Hellin'},
  {'name_ru': 'Эрнани', 'name_en': 'Hernani', 'name_sp': 'Hernani'},
  {
    'name_ru': 'Инохоса-дель-Дуке',
    'name_en': 'Hinojosa del Duque',
    'name_sp': 'Hinojosa del Duque'
  },
  {
    'name_ru': 'Оркахо-де-Сантъяго',
    'name_en': 'Horcajo de Santiago',
    'name_sp': 'Horcajo de Santiago'
  },
  {
    'name_ru': 'Оркахо-де-ла-Сьерра',
    'name_en': 'Horcajo de la Sierra',
    'name_sp': 'Horcajo de la Sierra'
  },
  {
    'name_ru': 'Оркахо-де-лос-Монтес',
    'name_en': 'Horcajo de los Montes',
    'name_sp': 'Horcajo de los Montes'
  },
  {
    'name_ru': 'Оркахухело-де-ла-Сьерра',
    'name_en': 'Horcajuelo de la Sierra',
    'name_sp': 'Horcajuelo de la Sierra'
  },
  {'name_ru': 'Уэска', 'name_en': 'Huesca', 'name_sp': 'Huesca'},
  {'name_ru': 'Уэльва', 'name_en': 'Huelva', 'name_sp': 'Huelva'},
  {
    'name_ru': 'Уэркаль-де-Альмерия',
    'name_en': 'Huercal de Almeria',
    'name_sp': 'Huercal de Almeria'
  },
  {
    'name_ru': 'Уэркаль-Овера',
    'name_en': 'Huercal-Overa',
    'name_sp': 'Huercal-Overa'
  },
  {
    'name_ru': 'Икод-де-лос-Винос',
    'name_en': 'Icod de los Vinos',
    'name_sp': 'Icod de los Vinos'
  },
  {
    'name_ru': 'Иглесуэла-дель-Сид',
    'name_en': 'Iglesuela del Cid',
    'name_sp': 'Iglesuela del Cid'
  },
  {'name_ru': 'Игуаллада', 'name_en': 'Igualada', 'name_sp': 'Igualada'},
  {'name_ru': 'Ильескас', 'name_en': 'Illescas', 'name_sp': 'Illescas'},
  {'name_ru': 'Ильора', 'name_en': 'Illora', 'name_sp': 'Illora'},
  {'name_ru': 'Инхенио', 'name_en': 'Ingenio', 'name_sp': 'Ingenio'},
  {'name_ru': 'Иннглес', 'name_en': 'Ingles', 'name_sp': 'Ingles'},
  {'name_ru': 'Ирун', 'name_en': 'Irun', 'name_sp': 'Irun'},
  {
    'name_ru': 'Исла-Кристина',
    'name_en': 'Isla Cristina',
    'name_sp': 'Isla Cristina'
  },
  {'name_ru': 'Исора', 'name_en': 'Isora', 'name_sp': 'Isora'},
  {'name_ru': 'Исла-Плана', 'name_en': 'Isla Plana', 'name_sp': 'Isla Plana'},
  {'name_ru': 'Итурен', 'name_en': 'Ituren', 'name_sp': 'Ituren'},
  {'name_ru': 'Изнахар', 'name_en': 'Iznajar', 'name_sp': 'Iznajar'},
  {'name_ru': 'Изнатораф', 'name_en': 'Iznatoraf', 'name_sp': 'Iznatoraf'},
  {'name_ru': 'Хаэн', 'name_en': 'Jaén', 'name_sp': 'Jaén'},
  {'name_ru': 'Хавея', 'name_en': 'Javea', 'name_sp': 'Javea'},
  {
    'name_ru': 'Херес-де-ла-Фронтера',
    'name_en': 'Jerez de la Frontera',
    'name_sp': 'Jerez de la Frontera'
  },
  {'name_ru': 'Хихона', 'name_en': 'Jijona', 'name_sp': 'Jijona'},
  {'name_ru': 'Ходор', 'name_en': 'Jodar', 'name_sp': 'Jodar'},
  {'name_ru': 'Хумилья', 'name_en': 'Jumilla', 'name_sp': 'Jumilla'},
  {'name_ru': 'Хун', 'name_en': 'Jun', 'name_sp': 'Jun'},
  {'name_ru': 'Ла Алгаба', 'name_en': 'La Algaba', 'name_sp': 'La Algaba'},
  {
    'name_ru': 'Ла Альмуния-де-Донья-Година',
    'name_en': 'La Almunia de Doña Godina',
    'name_sp': 'La Almunia de Doña Godina'
  },
  {'name_ru': 'Ла Анти́лья', 'name_en': 'La Antilla', 'name_sp': 'La Antilla'},
  {'name_ru': 'Ла-Корунья', 'name_en': 'La Coruña', 'name_sp': 'La Coruña'},
  {
    'name_ru': 'Ла Фронтера',
    'name_en': 'La Frontera',
    'name_sp': 'La Frontera'
  },
  {'name_ru': 'Ла Гомера', 'name_en': 'La Gomera', 'name_sp': 'La Gomera'},
  {
    'name_ru': 'Ла Лантехуэла',
    'name_en': 'La Lantejuela',
    'name_sp': 'La Lantejuela'
  },
  {
    'name_ru': 'Ла Линия-де-ла-Консепсьон',
    'name_en': 'La Línea de la Concepción',
    'name_sp': 'La Línea de la Concepción'
  },
  {
    'name_ru': 'Ла Луизиана',
    'name_en': 'La Luisiana',
    'name_sp': 'La Luisiana'
  },
  {'name_ru': 'Ла Мата', 'name_en': 'La Mata', 'name_sp': 'La Mata'},
  {'name_ru': 'Ла Олива', 'name_en': 'La Oliva', 'name_sp': 'La Oliva'},
  {
    'name_ru': 'Ла Пальма-дель-Кондадо',
    'name_en': 'La Palma del Condado',
    'name_sp': 'La Palma del Condado'
  },
  {
    'name_ru': 'Ла Публа-де-Альморадиель',
    'name_en': 'La Puebla de Almoradiel',
    'name_sp': 'La Puebla de Almoradiel'
  },
  {'name_ru': 'Ла Рода', 'name_en': 'La Roda', 'name_sp': 'La Roda'},
  {'name_ru': 'Ла Романа', 'name_en': 'La Romana', 'name_sp': 'La Romana'},
  {'name_ru': 'Ла Солана', 'name_en': 'La Solana', 'name_sp': 'La Solana'},
  {'name_ru': 'Ла Таха', 'name_en': 'La Taha', 'name_sp': 'La Taha'},
  {'name_ru': 'Ла Уньон', 'name_en': 'La Union', 'name_sp': 'La Union'},
  {
    'name_ru': 'Ла Валь-дель-Ухо',
    'name_en': 'La Vall de Uxo',
    'name_sp': 'La Vall de Uxo'
  },
  {'name_ru': 'Ланхарон', 'name_en': 'Lanjaron', 'name_sp': 'Lanjaron'},
  {'name_ru': 'Ларедо', 'name_en': 'Laredo', 'name_sp': 'Laredo'},
  {
    'name_ru': 'Лас Гальетас',
    'name_en': 'Las Galletas',
    'name_sp': 'Las Galletas'
  },
  {
    'name_ru': 'Лас Нориас-де-Даза',
    'name_en': 'Las Norias de Daza',
    'name_sp': 'Las Norias de Daza'
  },
  {
    'name_ru': 'Лас-Пальмас-де-Гран-Канария',
    'name_en': 'Las Palmas de Gran Canaria',
    'name_sp': 'Las Palmas de Gran Canaria'
  },
  {
    'name_ru': 'Лас Розас-де-Мадрид',
    'name_en': 'Las Rozas de Madrid',
    'name_sp': 'Las Rozas de Madrid'
  },
  {
    'name_ru': 'Лас Торрес-де-Котильяс',
    'name_en': 'Las Torres de Cotillas',
    'name_sp': 'Las Torres de Cotillas'
  },
  {'name_ru': 'Ласкао', 'name_en': 'Lazkao', 'name_sp': 'Lazkao'},
  {'name_ru': 'Лаза', 'name_en': 'Laza', 'name_sp': 'Laza'},
  {'name_ru': 'Лебриха', 'name_en': 'Lebrija', 'name_sp': 'Lebrija'},
  {'name_ru': 'Лекейтио', 'name_en': 'Lekeitio', 'name_sp': 'Lekeitio'},
  {'name_ru': 'Леон', 'name_en': 'Leon', 'name_sp': 'Leon'},
  {'name_ru': 'Лерма', 'name_en': 'Lerma', 'name_sp': 'Lerma'},
  {'name_ru': 'Линарес', 'name_en': 'Linares', 'name_sp': 'Linares'},
  {'name_ru': 'Льейда', 'name_en': 'Lleida', 'name_sp': 'Lleida'},
  {'name_ru': 'Лоэхес', 'name_en': 'Loeches', 'name_sp': 'Loeches'},
  {
    'name_ru': 'Лора-дель-Рио',
    'name_en': 'Lora del Rio',
    'name_sp': 'Lora del Rio'
  },
  {'name_ru': 'Лорча', 'name_en': 'Lorcha', 'name_sp': 'Lorcha'},
  {
    'name_ru': 'Лос-Алкасарес',
    'name_en': 'Los Alcázares',
    'name_sp': 'Los Alcázares'
  },
  {
    'name_ru': 'Лос Барриос',
    'name_en': 'Los Barrios',
    'name_sp': 'Los Barrios'
  },
  {
    'name_ru': 'Лос Корралес',
    'name_en': 'Los Corrales',
    'name_sp': 'Los Corrales'
  },
  {
    'name_ru': 'Лос Корралес де Бельуна',
    'name_en': 'Los Corrales de Buelna',
    'name_sp': 'Los Corrales de Buelna'
  },
  {
    'name_ru': 'Лос Кристрианос',
    'name_en': 'Los Cristianos',
    'name_sp': 'Los Cristianos'
  },
  {
    'name_ru': 'Лос Льянос де Аридан',
    'name_en': 'Los Llanos de Aridane',
    'name_sp': 'Los Llanos de Aridane'
  },
  {
    'name_ru': 'Лос Монтерас',
    'name_en': 'Los Monteros',
    'name_sp': 'Los Monteros'
  },
  {
    'name_ru': 'Лос Палачиос и Вильяфранка',
    'name_en': 'Los Palacios y Villafranca',
    'name_sp': 'Los Palacios y Villafranca'
  },
  {
    'name_ru': 'Лос Реалеос',
    'name_en': 'Los Realejos',
    'name_sp': 'Los Realejos'
  },
  {'name_ru': 'Лозойя', 'name_en': 'Lozoya', 'name_sp': 'Lozoya'},
  {'name_ru': 'Лозойюэла', 'name_en': 'Lozoyuela', 'name_sp': 'Lozoyuela'},
  {'name_ru': 'Лусена', 'name_en': 'Lucena', 'name_sp': 'Lucena'},
  {'name_ru': 'Луго', 'name_en': 'Lugo', 'name_sp': 'Lugo'},
  {'name_ru': 'Лумбрерас', 'name_en': 'Lumbreras', 'name_sp': 'Lumbreras'},
  {'name_ru': 'Лукэ', 'name_en': 'Luque', 'name_sp': 'Luque'},
  {'name_ru': 'Мадрид', 'name_en': 'Madrid', 'name_sp': 'Madrid'},
  {'name_ru': 'Маган', 'name_en': 'Magan', 'name_sp': 'Magan'},
  {'name_ru': 'Махон', 'name_en': 'Mahón', 'name_sp': 'Mahón'},
  {'name_ru': 'Малага', 'name_en': 'Malaga', 'name_sp': 'Malaga'},
  {'name_ru': 'Манча Реал', 'name_en': 'Mancha Real', 'name_sp': 'Mancha Real'},
  {
    'name_ru': 'Манча Вьеха',
    'name_en': 'Mancha Vieja',
    'name_sp': 'Mancha Vieja'
  },
  {'name_ru': 'Манисес', 'name_en': 'Manises', 'name_sp': 'Manises'},
  {
    'name_ru': 'Плайя-де-Аро',
    'name_en': 'Playa de Aro',
    'name_sp': 'Playa de Aro'
  },
  {
    'name_ru': 'Побла-де-Фарнальс',
    'name_en': 'Pobla de Farnals',
    'name_sp': 'Pobla de Farnals'
  },
  {
    'name_ru': 'Побла-де-Вальбона',
    'name_en': 'Pobla de Vallbona',
    'name_sp': 'Pobla de Vallbona'
  },
  {
    'name_ru': 'Побле Ноу дель Дельта',
    'name_en': 'Poble Nou del Delta',
    'name_sp': 'Poble Nou del Delta'
  },
  {
    'name_ru': 'Побра до Караменьял',
    'name_en': 'Pobra do Caramiñal',
    'name_sp': 'Pobra do Caramiñal'
  },
  {'name_ru': 'Понферрада', 'name_en': 'Ponferrada', 'name_sp': 'Ponferrada'},
  {
    'name_ru': 'Понт-де-Суэрт',
    'name_en': 'Pont de Suert',
    'name_sp': 'Pont de Suert'
  },
  {
    'name_ru': 'Понтесесурес',
    'name_en': 'Pontecesures',
    'name_sp': 'Pontecesures'
  },
  {'name_ru': 'Поркуна', 'name_en': 'Porcuna', 'name_sp': 'Porcuna'},
  {'name_ru': 'Поррино', 'name_en': 'Porriño', 'name_sp': 'Porriño'},
  {
    'name_ru': 'Порталс Нус',
    'name_en': 'Portals Nous',
    'name_sp': 'Portals Nous'
  },
  {'name_ru': 'Портильо', 'name_en': 'Portillo', 'name_sp': 'Portillo'},
  {
    'name_ru': 'Португалете',
    'name_en': 'Portugalete',
    'name_sp': 'Portugalete'
  },
  {'name_ru': 'Пасо Алкон', 'name_en': 'Pozo Alcon', 'name_sp': 'Pozo Alcon'},
  {'name_ru': 'Позобланко', 'name_en': 'Pozoblanco', 'name_sp': 'Pozoblanco'},
  {
    'name_ru': 'Позуэло де Аларкон',
    'name_en': 'Pozuelo de Alarcon',
    'name_sp': 'Pozuelo de Alarcon'
  },
  {
    'name_ru': 'Пасо Эстрехо',
    'name_en': 'Pozo Estrecho',
    'name_sp': 'Pozo Estrecho'
  },
  {
    'name_ru': 'Приего де Кордоба',
    'name_en': 'Priego de Cordoba',
    'name_sp': 'Priego de Cordoba'
  },
  {'name_ru': 'Пруна', 'name_en': 'Pruna', 'name_sp': 'Pruna'},
  {'name_ru': 'Пучоль', 'name_en': 'Puçol', 'name_sp': 'Puçol'},
  {
    'name_ru': 'Пуэбла-де-Касалья',
    'name_en': 'Puebla de Cazalla',
    'name_sp': 'Puebla de Cazalla'
  },
  {
    'name_ru': 'Пуэбла-де-Дон-Фадрике',
    'name_en': 'Puebla de Don Fadrique',
    'name_sp': 'Puebla de Don Fadrique'
  },
  {
    'name_ru': 'Пуэбла-де-Санчо Перес',
    'name_en': 'Puebla de Sancho Perez',
    'name_sp': 'Puebla de Sancho Perez'
  },
  {
    'name_ru': 'Пуэбла-дель-Рио',
    'name_en': 'Puebla del Rio',
    'name_sp': 'Puebla del Rio'
  },
  {
    'name_ru': 'Пунте Хенил',
    'name_en': 'Puente Genil',
    'name_sp': 'Puente Genil'
  },
  {
    'name_ru': 'Пуэрто-де-ла-Крус',
    'name_en': 'Puerto de la Cruz',
    'name_sp': 'Puerto de la Cruz'
  },
  {
    'name_ru': 'Пуэрто-де-ла-Дукесса',
    'name_en': 'Puerto de la Duquesa',
    'name_sp': 'Puerto de la Duquesa'
  },
  {
    'name_ru': 'Пуэрто-де-Масаррон',
    'name_en': 'Puerto de Mazarron',
    'name_sp': 'Puerto de Mazarron'
  },
  {
    'name_ru': 'Пуэрто-де-Сагунто',
    'name_en': 'Puerto de Sagunto',
    'name_sp': 'Puerto de Sagunto'
  },
  {
    'name_ru': 'Пуэрто-дель-Кармен',
    'name_en': 'Puerto del Carmen',
    'name_sp': 'Puerto del Carmen'
  },
  {
    'name_ru': 'Пуэрто Лумбрерас',
    'name_en': 'Puerto Lumbreras',
    'name_sp': 'Puerto Lumbreras'
  },
  {'name_ru': 'Пуигсерда', 'name_en': 'Puigcerda', 'name_sp': 'Puigcerda'},
  {
    'name_ru': 'Пуиг-де-Рос',
    'name_en': 'Puig de Ros',
    'name_sp': 'Puig de Ros'
  },
  {
    'name_ru': 'Пунта Прима',
    'name_en': 'Punta Prima',
    'name_sp': 'Punta Prima'
  },
  {'name_ru': 'Пурульена', 'name_en': 'Purullena', 'name_sp': 'Purullena'},
  {
    'name_ru': 'Кварт-де-Поблет',
    'name_en': 'Quart de Poblet',
    'name_sp': 'Quart de Poblet'
  },
  {'name_ru': 'Кесада', 'name_en': 'Quesada', 'name_sp': 'Quesada'},
  {'name_ru': 'Рафаэль', 'name_en': 'Rafal', 'name_sp': 'Rafal'},
  {
    'name_ru': 'Рамалес-де-ла-Виктория',
    'name_en': 'Ramales de la Victoria',
    'name_sp': 'Ramales de la Victoria'
  },
  {'name_ru': 'Редондела', 'name_en': 'Redondela', 'name_sp': 'Redondela'},
  {'name_ru': 'Рекена', 'name_en': 'Requena', 'name_sp': 'Requena'},
  {'name_ru': 'Реус', 'name_en': 'Reus', 'name_sp': 'Reus'},
  {'name_ru': 'Рибадео', 'name_en': 'Ribadeo', 'name_sp': 'Ribadeo'},
  {'name_ru': 'Рианхо', 'name_en': 'Rianxo', 'name_sp': 'Rianxo'},
  {
    'name_ru': 'Рибаррожа-дель-Турия',
    'name_en': 'Ribarroja del Turia',
    'name_sp': 'Ribarroja del Turia'
  },
  {
    'name_ru': 'Риба-Роха-дель-Турия',
    'name_en': 'Riba-roja de Turia',
    'name_sp': 'Riba-roja de Turia'
  },
  {
    'name_ru': 'Ринкон-де-ла-Виктория',
    'name_en': 'Rincon de la Victoria',
    'name_sp': 'Rincon de la Victoria'
  },
  {
    'name_ru': 'Ринкон-де-ла-Виктория',
    'name_en': 'Rincón de la Victoria',
    'name_sp': 'Rincón de la Victoria'
  },
  {
    'name_ru': 'Ривас-Васямадрид',
    'name_en': 'Rivas-Vaciamadrid',
    'name_sp': 'Rivas-Vaciamadrid'
  },
  {'name_ru': 'Роалес', 'name_en': 'Roales', 'name_sp': 'Roales'},
  {
    'name_ru': 'Роалес-де-Кампос',
    'name_en': 'Roales de Campos',
    'name_sp': 'Roales de Campos'
  },
  {
    'name_ru': 'Рокетас-де-Мар',
    'name_en': 'Roquetas de Mar',
    'name_sp': 'Roquetas de Mar'
  },
  {'name_ru': 'Рота', 'name_en': 'Rota', 'name_sp': 'Rota'},
  {'name_ru': 'Руби', 'name_en': 'Rubi', 'name_sp': 'Rubi'},
  {'name_ru': 'Руте', 'name_en': 'Rute', 'name_sp': 'Rute'},
  {'name_ru': 'Сабадель', 'name_en': 'Sabadell', 'name_sp': 'Sabadell'},
  {'name_ru': 'Саберо', 'name_en': 'Sabero', 'name_sp': 'Sabero'},
  {'name_ru': 'Сада', 'name_en': 'Sada', 'name_sp': 'Sada'},
  {'name_ru': 'Сагунто', 'name_en': 'Sagunto', 'name_sp': 'Sagunto'},
  {'name_ru': 'Саламанка', 'name_en': 'Salamanca', 'name_sp': 'Salamanca'},
  {
    'name_ru': 'Сальседа-де-Каселас',
    'name_en': 'Salceda de Caselas',
    'name_sp': 'Salceda de Caselas'
  },
  {'name_ru': 'Салинас', 'name_en': 'Salinas', 'name_sp': 'Salinas'},
  {'name_ru': 'Салобреña', 'name_en': 'Salobrena', 'name_sp': 'Salobrena'},
  {'name_ru': 'Сальтерос', 'name_en': 'Salteras', 'name_sp': 'Salteras'},
  {'name_ru': 'Сан Адриан', 'name_en': 'San Adrian', 'name_sp': 'San Adrian'},
  {
    'name_ru': 'Сан Агустин',
    'name_en': 'San Agustin',
    'name_sp': 'San Agustin'
  },
  {
    'name_ru': 'Сан Бартоломе',
    'name_en': 'San Bartolome',
    'name_sp': 'San Bartolome'
  },
  {
    'name_ru': 'Сан Бартоломе де Тирана',
    'name_en': 'San Bartolomé de Tirajana',
    'name_sp': 'San Bartolomé de Tirajana'
  },
  {
    'name_ru': 'Сан Кристобаль де Ла Лагуна',
    'name_en': 'San Cristobal de La Laguna',
    'name_sp': 'San Cristobal de La Laguna'
  },
  {
    'name_ru': 'Сан Фульхенсио',
    'name_en': 'San Fulgencio',
    'name_sp': 'San Fulgencio'
  },
  {'name_ru': 'Сан Хавьер', 'name_en': 'San Javier', 'name_sp': 'San Javier'},
  {'name_ru': 'Сан Хуан', 'name_en': 'San Juan', 'name_sp': 'San Juan'},
  {
    'name_ru': 'Сан Лоренсо-дель-Эскориал',
    'name_en': 'San Lorenzo de El Escorial',
    'name_sp': 'San Lorenzo de El Escorial'
  },
  {
    'name_ru': 'Сан Луис-де-Сабинильяс',
    'name_en': 'San Luis de Sabinillas',
    'name_sp': 'San Luis de Sabinillas'
  },
  {
    'name_ru': 'Сан Мартин-де-Вальдеиглесиас',
    'name_en': 'San Martin de Valdeiglesias',
    'name_sp': 'San Martin de Valdeiglesias'
  },
  {'name_ru': 'Сан Матео', 'name_en': 'San Mateo', 'name_sp': 'San Mateo'},
  {'name_ru': 'Сан Мигель', 'name_en': 'San Miguel', 'name_sp': 'San Miguel'},
  {
    'name_ru': 'Сан Мигель-де-Абона',
    'name_en': 'San Miguel de Abona',
    'name_sp': 'San Miguel de Abona'
  },
  {
    'name_ru': 'Сан Педро-де-Алькантара',
    'name_en': 'San Pedro de Alcantara',
    'name_sp': 'San Pedro de Alcantara'
  },
  {
    'name_ru': 'Сан Педро-дель-Пинаатар',
    'name_en': 'San Pedro del Pinatar',
    'name_sp': 'San Pedro del Pinatar'
  },
  {'name_ru': 'Сан Роке', 'name_en': 'San Roque', 'name_sp': 'San Roque'},
  {
    'name_ru': 'Сан Себастьян',
    'name_en': 'San Sebastian',
    'name_sp': 'San Sebastian'
  },
  {
    'name_ru': 'Сан Висенте-дель-Распейг',
    'name_en': 'San Vicente del Raspeig',
    'name_sp': 'San Vicente del Raspeig'
  },
  {'name_ru': 'Санженхо', 'name_en': 'Sanxenxo', 'name_sp': 'Sanxenxo'},
  {
    'name_ru': 'Сант Андреу-де-ла-Барка',
    'name_en': 'Sant Andreu de la Barca',
    'name_sp': 'Sant Andreu de la Barca'
  },
  {
    'name_ru': 'Сант Антонио-де-Портмани',
    'name_en': 'Sant Antoni de Portmany',
    'name_sp': 'Sant Antoni de Portmany'
  },
  {
    'name_ru': 'Сант Бой-де-Льобрегат',
    'name_en': 'Sant Boi de Llobregat',
    'name_sp': 'Sant Boi de Llobregat'
  },
  {
    'name_ru': 'Сант Карлос-де-ла-Рапита',
    'name_en': 'Sant Carles de la Ràpita',
    'name_sp': 'Sant Carles de la Ràpita'
  },
  {
    'name_ru': 'Сант Кугат-дель-Вальес',
    'name_en': 'Sant Cugat del Vallès',
    'name_sp': 'Sant Cugat del Vallès'
  },
  {
    'name_ru': 'Сант Фелиу-де-Гиксольс',
    'name_en': 'Sant Feliu de Guixols',
    'name_sp': 'Sant Feliu de Guixols'
  },
  {
    'name_ru': 'Сант Фелиу-де-Льобрегат',
    'name_en': 'Sant Feliu de Llobregat',
    'name_sp': 'Sant Feliu de Llobregat'
  },
  {
    'name_ru': 'Сант Хуан-де-Алькант',
    'name_en': 'Sant Joan d’Alacant',
    'name_sp': 'Sant Joan d’Alacant'
  },
  {
    'name_ru': 'Сант Жуст Десверн',
    'name_en': 'Sant Just Desvern',
    'name_sp': 'Sant Just Desvern'
  },
  {
    'name_ru': 'Сант Пере-де-Рибес',
    'name_en': 'Sant Pere de Ribes',
    'name_sp': 'Sant Pere de Ribes'
  },
  {
    'name_ru': 'Санта-Бригида',
    'name_en': 'Santa Brigida',
    'name_sp': 'Santa Brigida'
  },
  {
    'name_ru': 'Санта-Колома-де-Граменет',
    'name_en': 'Santa Coloma de Gramenet',
    'name_sp': 'Santa Coloma de Gramenet'
  },
  {
    'name_ru': 'Санта-Крус-де-Тенерифе',
    'name_en': 'Santa Cruz de Tenerife',
    'name_sp': 'Santa Cruz de Tenerife'
  },
  {
    'name_ru': 'Санта-Эулалия-дель-Рио',
    'name_en': 'Santa Eulalia del Rio',
    'name_sp': 'Santa Eulalia del Rio'
  },
  {
    'name_ru': 'Санта-Лусия',
    'name_en': 'Santa Lucia',
    'name_sp': 'Santa Lucia'
  },
  {
    'name_ru': 'Санта-Маргарита-де-Монбюи',
    'name_en': 'Santa Margarida de Montbui',
    'name_sp': 'Santa Margarida de Montbui'
  },
  {
    'name_ru': 'Санта-Мария-де-Палатордера',
    'name_en': 'Santa Maria de Palautordera',
    'name_sp': 'Santa Maria de Palautordera'
  },
  {
    'name_ru': 'Санта-Мария-дель-Ками',
    'name_en': 'Santa Maria del Cami',
    'name_sp': 'Santa Maria del Cami'
  },
  {'name_ru': 'Санта-Пола', 'name_en': 'Santa Pola', 'name_sp': 'Santa Pola'},
  {
    'name_ru': 'Санта-Понса',
    'name_en': 'Santa Ponsa',
    'name_sp': 'Santa Ponsa'
  },
  {
    'name_ru': 'Санта-Сусана',
    'name_en': 'Santa Susanna',
    'name_sp': 'Santa Susanna'
  },
  {
    'name_ru': 'Сантьяго-де-Компостела',
    'name_en': 'Santiago de Compostela',
    'name_sp': 'Santiago de Compostela'
  },
  {
    'name_ru': 'Сантьяго-дель-Тейде',
    'name_en': 'Santiago del Teide',
    'name_sp': 'Santiago del Teide'
  },
  {'name_ru': 'Сантомера', 'name_en': 'Santomera', 'name_sp': 'Santomera'},
  {'name_ru': 'Сантуртси', 'name_en': 'Santurtzi', 'name_sp': 'Santurtzi'},
  {
    'name_ru': 'Сан Висенте-дельс-Орц',
    'name_en': 'Sant Vicenç dels Horts',
    'name_sp': 'Sant Vicenç dels Horts'
  },
  {'name_ru': 'Сантани', 'name_en': 'Santanyi', 'name_sp': 'Santanyi'},
  {'name_ru': 'Сантарем', 'name_en': 'Santarem', 'name_sp': 'Santarem'},
  {
    'name_ru': 'Сантовения-де-Писуэрга',
    'name_en': 'Santovenia de Pisuerga',
    'name_sp': 'Santovenia de Pisuerga'
  },
  {'name_ru': 'Сантпедор', 'name_en': 'Santpedor', 'name_sp': 'Santpedor'},
  {'name_ru': 'Санженхо', 'name_en': 'Sanxenxo', 'name_sp': 'Sanxenxo'},
  {'name_ru': 'Саррия', 'name_en': 'Sarria', 'name_sp': 'Sarria'},
  {'name_ru': 'Сарригурен', 'name_en': 'Sarriguren', 'name_sp': 'Sarriguren'},
  {'name_ru': 'Сесе́ня', 'name_en': 'Seseña', 'name_sp': 'Seseña'},
  {'name_ru': 'Севилья', 'name_en': 'Seville', 'name_sp': 'Seville'},
  {'name_ru': 'Сьерра', 'name_en': 'Sierra', 'name_sp': 'Sierra'},
  {
    'name_ru': 'Сьерра-де-Йегвас',
    'name_en': 'Sierra de Yeguas',
    'name_sp': 'Sierra de Yeguas'
  },
  {'name_ru': 'Сьете-Огас', 'name_en': 'Siete Aguas', 'name_sp': 'Siete Aguas'},
  {'name_ru': 'Силос', 'name_en': 'Silos', 'name_sp': 'Silos'},
  {'name_ru': 'Синеу', 'name_en': 'Sineu', 'name_sp': 'Sineu'},
  {'name_ru': 'Ситгес', 'name_en': 'Sitges', 'name_sp': 'Sitges'},
  {'name_ru': 'Сольяна', 'name_en': 'Sollana', 'name_sp': 'Sollana'},
  {'name_ru': 'Сольер', 'name_en': 'Soller', 'name_sp': 'Soller'},
  {'name_ru': 'Солсона', 'name_en': 'Solsona', 'name_sp': 'Solsona'},
  {
    'name_ru': 'Сон-Сервера',
    'name_en': 'Son Servera',
    'name_sp': 'Son Servera'
  },
  {'name_ru': 'Сопелана', 'name_en': 'Sopelana', 'name_sp': 'Sopelana'},
  {'name_ru': 'Сория', 'name_en': 'Soria', 'name_sp': 'Soria'},
  {'name_ru': 'Сорихуэла', 'name_en': 'Sorihuela', 'name_sp': 'Sorihuela'},
  {
    'name_ru': 'Сотильо-де-ла-Адада',
    'name_en': 'Sotillo de la Adrada',
    'name_sp': 'Sotillo de la Adrada'
  },
  {'name_ru': 'Суансес', 'name_en': 'Suances', 'name_sp': 'Suances'},
  {'name_ru': 'Суэка', 'name_en': 'Sueca', 'name_sp': 'Sueca'},
  {'name_ru': 'Табернас', 'name_en': 'Tabernas', 'name_sp': 'Tabernas'},
  {'name_ru': 'Такоронте', 'name_en': 'Tacoronte', 'name_sp': 'Tacoronte'},
  {
    'name_ru': 'Талавера-де-ла-Рейна',
    'name_en': 'Talavera de la Reina',
    'name_sp': 'Talavera de la Reina'
  },
  {
    'name_ru': 'Талавера-ла-Реаль',
    'name_en': 'Talavera la Real',
    'name_sp': 'Talavera la Real'
  },
  {'name_ru': 'Тараделл', 'name_en': 'Taradell', 'name_sp': 'Taradell'},
  {'name_ru': 'Таразона', 'name_en': 'Tarazona', 'name_sp': 'Tarazona'},
  {'name_ru': 'Таррагона', 'name_en': 'Tarragona', 'name_sp': 'Tarragona'},
  {'name_ru': 'Таррега', 'name_en': 'Tarrega', 'name_sp': 'Tarrega'},
  {'name_ru': 'Тегуэсте', 'name_en': 'Tegueste', 'name_sp': 'Tegueste'},
  {'name_ru': 'Техина', 'name_en': 'Tejina', 'name_sp': 'Tejina'},
  {'name_ru': 'Тельде', 'name_en': 'Telde', 'name_sp': 'Telde'},
  {'name_ru': 'Тенерифе', 'name_en': 'Tenerife', 'name_sp': 'Tenerife'},
  {'name_ru': 'Терор', 'name_en': 'Teror', 'name_sp': 'Teror'},
  {'name_ru': 'Терраса', 'name_en': 'Terrassa', 'name_sp': 'Terrassa'},
  {'name_ru': 'Теруэль', 'name_en': 'Teruel', 'name_sp': 'Teruel'},
  {'name_ru': 'Тетуан', 'name_en': 'Tetuan', 'name_sp': 'Tetuan'},
  {'name_ru': 'Тиас', 'name_en': 'Tias', 'name_sp': 'Tias'},
  {'name_ru': 'Тиби', 'name_en': 'Tibi', 'name_sp': 'Tibi'},
  {
    'name_ru': 'Тихоко-Бахо',
    'name_en': 'Tijoco Bajo',
    'name_sp': 'Tijoco Bajo'
  },
  {'name_ru': 'Тинахо', 'name_en': 'Tinajo', 'name_sp': 'Tinajo'},
  {'name_ru': 'Тинео', 'name_en': 'Tineo', 'name_sp': 'Tineo'},
  {'name_ru': 'Тобарра', 'name_en': 'Tobarra', 'name_sp': 'Tobarra'},
  {'name_ru': 'Толокс', 'name_en': 'Tolox', 'name_sp': 'Tolox'},
  {'name_ru': 'Томарес', 'name_en': 'Tomares', 'name_sp': 'Tomares'},
  {'name_ru': 'Томельосо', 'name_en': 'Tomelloso', 'name_sp': 'Tomelloso'},
  {
    'name_ru': 'Торделесильяс',
    'name_en': 'Tordesillas',
    'name_sp': 'Tordesillas'
  },
  {
    'name_ru': 'Торре-дель-Мар',
    'name_en': 'Torre del Mar',
    'name_sp': 'Torre del Mar'
  },
  {
    'name_ru': 'Торре-Пахеко',
    'name_en': 'Torre Pacheco',
    'name_sp': 'Torre Pacheco'
  },
  {
    'name_ru': 'Торреперогиль',
    'name_en': 'Torreperogil',
    'name_sp': 'Torreperogil'
  },
  {
    'name_ru': 'ТорреКебрада',
    'name_en': 'Torrequebrada',
    'name_sp': 'Torrequebrada'
  },
  {
    'name_ru': 'Торрелавега',
    'name_en': 'Torrelavega',
    'name_sp': 'Torrelavega'
  },
  {
    'name_ru': 'Торрелодонес',
    'name_en': 'Torrelodones',
    'name_sp': 'Torrelodones'
  },
  {
    'name_ru': 'Торремолиноc',
    'name_en': 'Torremolinos',
    'name_sp': 'Torremolinos'
  },
  {
    'name_ru': 'Торремуэлья',
    'name_en': 'Torremuelle',
    'name_sp': 'Torremuelle'
  },
  {
    'name_ru': 'Торреперогиль',
    'name_en': 'Torreperogil',
    'name_sp': 'Torreperogil'
  },
  {
    'name_ru': 'Торрес-Торрес',
    'name_en': 'Torres Torres',
    'name_sp': 'Torres Torres'
  },
  {'name_ru': 'Торревьеха', 'name_en': 'Torrevieja', 'name_sp': 'Torrevieja'},
  {
    'name_ru': 'Торроэлла-де-Монтгри',
    'name_en': 'Torroella de Montgri',
    'name_sp': 'Torroella de Montgri'
  },
  {'name_ru': 'Торокс', 'name_en': 'Torrox', 'name_sp': 'Torrox'},
  {'name_ru': 'Тортоса', 'name_en': 'Tortosa', 'name_sp': 'Tortosa'},
  {'name_ru': 'Тотана', 'name_en': 'Totana', 'name_sp': 'Totana'},
  {'name_ru': 'Туро', 'name_en': 'Touro', 'name_sp': 'Touro'},
  {'name_ru': 'Тригерас', 'name_en': 'Trigueros', 'name_sp': 'Trigueros'},
  {'name_ru': 'Трухильо', 'name_en': 'Trujillo', 'name_sp': 'Trujillo'},
  {'name_ru': 'Туй', 'name_en': 'Tui', 'name_sp': 'Tui'},
  {'name_ru': 'Уэда', 'name_en': 'Ubeda', 'name_sp': 'Ubeda'},
  {'name_ru': 'Ухена', 'name_en': 'Ugena', 'name_sp': 'Ugena'},
  {'name_ru': 'Ульдекона', 'name_en': 'Ulldecona', 'name_sp': 'Ulldecona'},
  {'name_ru': 'Ульдекона', 'name_en': 'Ulldecona', 'name_sp': 'Ulldecona'},
  {'name_ru': 'Утебо', 'name_en': 'Utebo', 'name_sp': 'Utebo'},
  {'name_ru': 'Утрера', 'name_en': 'Utrera', 'name_sp': 'Utrera'},
  {'name_ru': 'Вальдеморо', 'name_en': 'Valdemoro', 'name_sp': 'Valdemoro'},
  {'name_ru': 'Вальдепенас', 'name_en': 'Valdepeñas', 'name_sp': 'Valdepeñas'},
  {
    'name_ru': 'Вальдерробрес',
    'name_en': 'Valderrobres',
    'name_sp': 'Valderrobres'
  },
  {'name_ru': 'Вальдови́нью', 'name_en': 'Valdoviño', 'name_sp': 'Valdoviño'},
  {'name_ru': 'Валенсия', 'name_en': 'Valencia', 'name_sp': 'Valencia'},
  {
    'name_ru': 'Валенсина-де-ла-Консепсьон',
    'name_en': 'Valencina de la Concepción',
    'name_sp': 'Valencina de la Concepción'
  },
  {'name_ru': 'Вальга', 'name_en': 'Valga', 'name_sp': 'Valga'},
  {
    'name_ru': 'Валле-де-Табладильо',
    'name_en': 'Valle de Tabladillo',
    'name_sp': 'Valle de Tabladillo'
  },
  {'name_ru': 'Вальекас', 'name_en': 'Vallecas', 'name_sp': 'Vallecas'},
  {
    'name_ru': 'Валь-де-Бои',
    'name_en': 'Vall de Boi',
    'name_sp': 'Vall de Boi'
  },
  {'name_ru': 'Вальядолид', 'name_en': 'Valladolid', 'name_sp': 'Valladolid'},
  {
    'name_ru': 'Валье-Гран-Рей',
    'name_en': 'Valle Gran Rey',
    'name_sp': 'Valle Gran Rey'
  },
  {
    'name_ru': 'Валье-Гуэра',
    'name_en': 'Valle Guerra',
    'name_sp': 'Valle Guerra'
  },
  {
    'name_ru': 'Вальеэрмосо',
    'name_en': 'Vallehermoso',
    'name_sp': 'Vallehermoso'
  },
  {'name_ru': 'Вальс', 'name_en': 'Valls', 'name_sp': 'Valls'},
  {'name_ru': 'Вальверде', 'name_en': 'Valverde', 'name_sp': 'Valverde'},
  {
    'name_ru': 'Вальверде-дель-Камино',
    'name_en': 'Valverde del Camino',
    'name_sp': 'Valverde del Camino'
  },
  {
    'name_ru': 'Вальсекильо',
    'name_en': 'Valsequillo',
    'name_sp': 'Valsequillo'
  },
  {
    'name_ru': 'Вальсекильо-де-Гран-Канария',
    'name_en': 'Valsequillo de Gran Canaria',
    'name_sp': 'Valsequillo de Gran Canaria'
  },
  {
    'name_ru': 'Велес-де-Бенаудалль',
    'name_en': 'Vélez de Benaudalla',
    'name_sp': 'Vélez de Benaudalla'
  },
  {
    'name_ru': 'Велес-Малага',
    'name_en': 'Velez-Malaga',
    'name_sp': 'Velez-Malaga'
  },
  {
    'name_ru': 'Велес-Рубио',
    'name_en': 'Vélez-Rubio',
    'name_sp': 'Vélez-Rubio'
  },
  {'name_ru': 'Вера', 'name_en': 'Vera', 'name_sp': 'Vera'},
  {
    'name_ru': 'Вера-де-Монкайо',
    'name_en': 'Vera de Moncayo',
    'name_sp': 'Vera de Moncayo'
  },
  {'name_ru': 'Верина', 'name_en': 'Verin', 'name_sp': 'Verin'},
  {'name_ru': 'Вик', 'name_en': 'Vic', 'name_sp': 'Vic'},
  {'name_ru': 'Виго', 'name_en': 'Vigo', 'name_sp': 'Vigo'},
  {'name_ru': 'Вилабоа', 'name_en': 'Vilaboa', 'name_sp': 'Vilaboa'},
  {'name_ru': 'Виладеканс', 'name_en': 'Viladecans', 'name_sp': 'Viladecans'},
  {
    'name_ru': 'Вилагартия-де-Ароуса',
    'name_en': 'Vilagarcia de Arousa',
    'name_sp': 'Vilagarcia de Arousa'
  },
  {'name_ru': 'Вилальба', 'name_en': 'Vilalba', 'name_sp': 'Vilalba'},
  {
    'name_ru': 'Виламаршант',
    'name_en': 'Vilamarxant',
    'name_sp': 'Vilamarxant'
  },
  {
    'name_ru': 'Вилланова-и-ла-Гельтру',
    'name_en': 'Vilanova i la Geltru',
    'name_sp': 'Vilanova i la Geltru'
  },
  {
    'name_ru': 'Вилланова-дель-Ками',
    'name_en': 'Vilanova del Cami',
    'name_sp': 'Vilanova del Cami'
  },
  {
    'name_ru': 'Вильябланка',
    'name_en': 'Villablanca',
    'name_sp': 'Villablanca'
  },
  {'name_ru': 'Вильябона', 'name_en': 'Villabona', 'name_sp': 'Villabona'},
  {'name_ru': 'Вильякана', 'name_en': 'Villacanas', 'name_sp': 'Villacanas'},
  {
    'name_ru': 'Вильякаррильо',
    'name_en': 'Villacarrillo',
    'name_sp': 'Villacarrillo'
  },
  {'name_ru': 'Вильядьего', 'name_en': 'Villadiego', 'name_sp': 'Villadiego'},
  {
    'name_ru': 'Вильягонзало-Педерналь',
    'name_en': 'Villagonzalo Pedernales',
    'name_sp': 'Villagonzalo Pedernales'
  },
  {
    'name_ru': 'Вильяхойоса',
    'name_en': 'Villajoyosa',
    'name_sp': 'Villajoyosa'
  },
  {
    'name_ru': 'Вильяльба-дель-Алькор',
    'name_en': 'Villalba del Alcor',
    'name_sp': 'Villalba del Alcor'
  },
  {'name_ru': 'Вильяпандо', 'name_en': 'Villalpando', 'name_sp': 'Villalpando'},
  {
    'name_ru': 'Вильялунга-де-ла-Сагра',
    'name_en': 'Villaluenga de la Sagra',
    'name_sp': 'Villaluenga de la Sagra'
  },
  {
    'name_ru': 'Вильянуэва-де-ла-Консепсьон',
    'name_en': 'Villanueva de la Concepcion',
    'name_sp': 'Villanueva de la Concepcion'
  },
  {
    'name_ru': 'Вильянуэва-де-ла-Серена',
    'name_en': 'Villanueva de la Serena',
    'name_sp': 'Villanueva de la Serena'
  },
  {
    'name_ru': 'Вильянуэва-де-лос-Кастильехос',
    'name_en': 'Villanueva de los Castillejos',
    'name_sp': 'Villanueva de los Castillejos'
  },
  {
    'name_ru': 'Вильянуэва-дель-Арискаль',
    'name_en': 'Villanueva del Ariscal',
    'name_sp': 'Villanueva del Ariscal'
  },
  {
    'name_ru': 'Вильянуэва-дель-Арзобиспо',
    'name_en': 'Villanueva del Arzobispo',
    'name_sp': 'Villanueva del Arzobispo'
  },
  {
    'name_ru': 'Вильянуэва-дель-Рей',
    'name_en': 'Villanueva del Rey',
    'name_sp': 'Villanueva del Rey'
  },
  {
    'name_ru': 'Вильянуэва-дель-Рио',
    'name_en': 'Villanueva del Rio',
    'name_sp': 'Villanueva del Rio'
  },
  {
    'name_ru': 'Вильянуэва-дель-Рио-и-Минас',
    'name_en': 'Villanueva del Rio y Minas',
    'name_sp': 'Villanueva del Rio y Minas'
  },
  {
    'name_ru': 'Вильянуэва-дель-Росарио',
    'name_en': 'Villanueva del Rosario',
    'name_sp': 'Villanueva del Rosario'
  },
  {
    'name_ru': 'Вильянуэва-де-Тапия',
    'name_en': 'Villanueva de Tapia',
    'name_sp': 'Villanueva de Tapia'
  },
  {
    'name_ru': 'Вильянуэва-де-ла-Торре',
    'name_en': 'Villanueva de la Torre',
    'name_sp': 'Villanueva de la Torre'
  },
  {
    'name_ru': 'Вильянуэва-де-лос-Инфантес',
    'name_en': 'Villanueva de los Infantes',
    'name_sp': 'Villanueva de los Infantes'
  },
  {
    'name_ru': 'Вильянуэва-Месия',
    'name_en': 'Villanueva Mesia',
    'name_sp': 'Villanueva Mesia'
  },
  {'name_ru': 'Вильяр Alto', 'name_en': 'Villaralto', 'name_sp': 'Villaralto'},
  {'name_ru': 'Вильярреал', 'name_en': 'Villareal', 'name_sp': 'Villareal'},
  {
    'name_ru': 'Вильярреал-де-Салванес',
    'name_en': 'Villarejo de Salvanés',
    'name_sp': 'Villarejo de Salvanés'
  },
  {'name_ru': 'Вильярреал', 'name_en': 'Villarreal', 'name_sp': 'Villarreal'},
  {
    'name_ru': 'Вильяррубия',
    'name_en': 'Villarrubia',
    'name_sp': 'Villarrubia'
  },
  {
    'name_ru': 'Вильяррубия-де-лос-Охос',
    'name_en': 'Villarrubia de los Ojos',
    'name_sp': 'Villarrubia de los Ojos'
  },
  {
    'name_ru': 'Вильярробледо',
    'name_en': 'Villarrobledo',
    'name_sp': 'Villarrobledo'
  },
  {
    'name_ru': 'Вильярророя-де-лос-Пинарас',
    'name_en': 'Villarroya de los Pinares',
    'name_sp': 'Villarroya de los Pinares'
  },
  {
    'name_ru': 'Вильясекилья',
    'name_en': 'Villasequilla',
    'name_sp': 'Villasequilla'
  },
  {
    'name_ru': 'Вильявиcьоса',
    'name_en': 'Villaviciosa',
    'name_sp': 'Villaviciosa'
  },
  {
    'name_ru': 'Вильявиcьоса-де-Одон',
    'name_en': 'Villaviciosa de Odon',
    'name_sp': 'Villaviciosa de Odon'
  },
  {'name_ru': 'Вильена', 'name_en': 'Villena', 'name_sp': 'Villena'},
  {'name_ru': 'Вильольдо', 'name_en': 'Villoldo', 'name_sp': 'Villoldo'},
  {'name_ru': 'Винарос', 'name_en': 'Vinaros', 'name_sp': 'Vinaros'},
  {'name_ru': 'Винарос', 'name_en': 'Vinaròs', 'name_sp': 'Vinaròs'},
  {
    'name_ru': 'Витория-Гастейс',
    'name_en': 'Vitoria-Gasteiz',
    'name_sp': 'Vitoria-Gasteiz'
  },
  {'name_ru': 'Вискайя', 'name_en': 'Vizcaya', 'name_sp': 'Vizcaya'},
  {'name_ru': 'Хабия', 'name_en': 'Xabia', 'name_sp': 'Xabia'},
  {'name_ru': 'Сатя', 'name_en': 'Xativa', 'name_sp': 'Xativa'},
  {'name_ru': 'Херако', 'name_en': 'Xeraco', 'name_sp': 'Xeraco'},
  {'name_ru': 'Хиривелья', 'name_en': 'Xirivella', 'name_sp': 'Xirivella'},
  {'name_ru': 'Юнкера', 'name_en': 'Yunquera', 'name_sp': 'Yunquera'},
  {'name_ru': 'Сафра', 'name_en': 'Zafra', 'name_sp': 'Zafra'},
  {'name_ru': 'Самора', 'name_en': 'Zamora', 'name_sp': 'Zamora'},
  {'name_ru': 'Сарагоса', 'name_en': 'Zaragoza', 'name_sp': 'Zaragoza'},
  {'name_ru': 'Зубия', 'name_en': 'Zubia', 'name_sp': 'Zubia'},
  {'name_ru': 'Зумая', 'name_en': 'Zumaia', 'name_sp': 'Zumaia'},
  {'name_ru': 'Сумаррага', 'name_en': 'Zumarraga', 'name_sp': 'Zumarraga'},
  {'name_ru': 'Зунеда', 'name_en': 'Zuñeda', 'name_sp': 'Zuñeda'},
];



//List citys =

//  db.collection('categories').insertMany([
//     {
//       'name_en': 'Wedding Photoshoot',
//       'name_ru': 'Свадебная фотосессия',
//       'name_sp': 'Sesión de fotos de boda',
//     },
//     {
//       'name_en': 'Advertising Shoot',
//       'name_ru': 'Рекламная съёмка',
//       'name_sp': 'Sesión de publicidad',
//     },
//     {
//       'name_en': 'Children\'s Photoshoot',
//       'name_ru': 'Детская фотосессия',
//       'name_sp': 'Sesión de fotos infantiles',
//     },
//     {
//       'name_en': 'Beauty',
//       'name_ru': 'Бьюти',
//       'name_sp': 'Belleza',
//     }
//   ]);

// router.get('/search/<query>/<lang>',
//     (Request request, String query, String lang) async {
//   String decodedData = Uri.decodeComponent(query);
//   final response = await db.collection('countries').find({
//     'name_$lang': {'\$regex': decodedData, '\$options': 'i'}
//   }).toList();
//
//   print(response);
//   return Response.ok('ok');
// });

// void addCitiesSp() async {
//   var db = Db("mongodb://localhost:27017/lens_map");
//   await db.open();
//
//   // Формируем список городов для добавления
//   var citiesToAdd = [];
//   for (var item in translations) {
//     citiesToAdd.add({
//       '_id': ObjectId(),
//       'name_ru': item['name_ru'],
//       'name_en': item['name_en'],
//       'name_sp': item['name_sp']
//     });
//   }
//
//   // Обновляем документ, добавляя новые города в массив cities
//   await db.collection('countries').update({
//     'name_sp': 'Spain'
//   }, {
//     r'$push': {
//       'cities': {r'$each': citiesToAdd}
//     }
//   });
//
//   await db.close();
// }
